Udated scripts to curent versions and add GPL v2 license.

diff --git a/battery-check b/battery-check
--- a/battery-check
+++ b/battery-check
@@ -1,173 +1,218 @@
-#!/bin/bash
+#!/usr/bin/env bash
 ###############################################################################
 # Script Name  : battery-check
 # Description  : Display charge and health statics of a laptop battery
-# Dependencies : None
-# Arguments    : None
-# Author       : Richard B. Romig, 28 Jul 2020
-# Email        : rick.romig@gmail.com
-# Comments     : Batttery health based on a script by Elias W (eliasw4u on Ezeetalk.com)
+# Dependencies : bc (not installed by default on BunsenLabs Beryllium)
+# Arguments    : -h, --help, -v --version
+# Author       : Copyright (C) 2020, Richard B. Romig, 28 Jul 2020
+# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
+# Comments     : Uses data from /sys/class/power_supply/BAT*
+#              : Batttery health based on a script by Elias W (eliasw4u on Ezeetalk.com)
 #              : Battery charge based on a script by Luke Smith (https://lukesmith.xyz)
-#              : Supports multiple batteries.
 # TODO (Rick)  :
-###############################################################################
-# Copyright (C) 2020, Richard B. Romig
+# License      : GNU General Public License, version 2
+# Copyright © 2023, Richard B. Romig
 # Email: rick.romig@gmail.com
-#
+# 
 # This program is free software; you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
 # the Free Software Foundation; either version 2 of the License, or
 # (at your option) any later version.
-#
+# 
 # This program is distributed in the hope that it will be useful,
 # but WITHOUT ANY WARRANTY; without even the implied warranty of
 # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 # GNU General Public License for more details.
-#
+# 
 # You should have received a copy of the GNU General Public License along
 # with this program. If not, see <https://www.gnu.org/licenses/>.
+###############################################################################
+
+# Shellcheck Directives ##
+# shellcheck source=/home/rick/bin/functionlib
+# shellcheck disable=SC1091
+
+## Load function library ##
+
+if [[ -x "$HOME/bin/functionlib" ]]; then
+  source "$HOME/bin/functionlib"
+else
+  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
+  exit 1
+fi
 
 ## Variables ##
 
-readonly SCRIPT=$(basename "$0")
-readonly VERSION="0.2.8"
-readonly UPDATED="21 Jan 2021"
+_script=$(basename "$0"); readonly _script
+readonly _version="0.6.2"
+readonly _updated="05 Oct 2023"
 
 ## Functions ##
 
 help() {
-  echo "$SCRIPT $VERSION, Upated: $UPDATED"
-  echo -e "\e[32mUsage:\e[0m $SCRIPT [option]"
-  echo -e "\e[33mOPTIONS\e[0m"
-  echo -e "$SCRIPT \t\t# displays battery health."
-  echo -e "$SCRIPT -h\t# displays this help message."
-  echo -e "$SCRIPT --help\t# displays this help message."
-  echo -e "$SCRIPT --version\t# displays the version and information about the script."
+  local errcode="${1:-2}"
+  cat <<- EOF
+  ${green}Usage:${normal} $_script [option]
+  With no argument, displays battery health information.
+  ${orange}OPTIONS:${normal}
+  -h        # displays this help message.
+  --help    # displays this help message.
+  -v        # displays the version and information about the script.
+  --version # displays the version and information about the script.
+  $_script $_version, Upated: $_updated
+EOF
+  exit "$errcode"
 }
 
 version() {
   cat <<- EOF
-  $SCRIPT $VERSION, Upated: $UPDATED
+  $_script $_version, Updated: $_updated
   Displays the charge state and health of a laptop battery using data obtained
-  from files in the /sys/class/power_supply/BAT*. Capacity information may shown
+  from files in /sys/class/power_supply/BAT*. Capacity information may be shown
   in either Ampere-hours (Ah) or Watt-hours (Wh), depending on your system.
 EOF
 }
 
-function die() {
-  local MSG="$1"	    # message
-  local EC=${2-1}	    # default exit status 1
-  echo -e "\e[91mERROR:\e[0m $MSG" >&2
-  exit "$EC"
-}
-
 battery_status() {
-  echo -e "\n\e[33mBattery charge:\e[0m"
-  [ -f "$BATTERY/status" ] || die "Problem with the battery! Replace it!"
-  BAT_STATUS=$(awk '{print $1}' "$BATTERY/status")
-  [ -f "$BATTERY/capacity" ] || die "Problem with the battery! Replace it!"
-  BAT_CHARGE=$(awk '{print $1}' "$BATTERY/capacity")
-  [[ "$BAT_STATUS" = "Discharging" && "$BAT_CHARGE" -le 25 ]] && WARN="\U26A0\UFE0F"
-  echo -e "\t\e[92mStatus:\e[0m $BAT_STATUS"
-  echo -e "\t\e[92mCharge:\e[0m $BAT_CHARGE%  $WARN"
+  printf "\n%sBattery charge:%s\n" "$orange" "$normal"
+  [[ -f "$battery_path/status" ]] || die "Problem with the battery! Replace it!"
+  bat_status=$(cat "$battery_path/status")
+  [[ -f "$battery_path/capacity" ]] || die "Problem with the battery! Replace it!"
+  bat_charge=$(cat "$battery_path/capacity")
+  [[ "$bat_status" == "Discharging" && "$bat_charge" -le 25 ]] && warn="\U26A0\UFE0F"
+  printf "\t%sStatus:%s %s\n" "$lightgreen" "$normal" "$bat_status"
+  printf "\t%sCharge:%s %s%%  %s\n" "$lightgreen" "$normal" "$bat_charge" "$warn"
 }
 
 battery_capacity() {
-  if [ -f "$BATTERY/charge_full" ]; then
-    ACTUAL_FULL="charge_full"
-    DESIGN_FULL="charge_full_design"
-    UNIT="Ah"
+  if [[ -f "$battery_path/charge_full" ]]; then
+    actual_full="charge_full"
+    design_full="charge_full_design"
+    unit="Ah"
   else
-    ACTUAL_FULL="energy_full"
-    DESIGN_FULL="energy_full_design"
-    UNIT="Wh"
+    actual_full="energy_full"
+    design_full="energy_full_design"
+    unit="Wh"
   fi
 
-  ACTUAL_MAX=$(awk 'NF{print $1/1000000}' OFMT="%2.2f" "$BATTERY/$ACTUAL_FULL")
-  DESIGN_MAX=$(awk 'NF{print $1/1000000}' OFMT="%2.2f" "$BATTERY/$DESIGN_FULL")
-  INT_DES="${DESIGN_MAX%%.*}"
-  INT_ACT="${ACTUAL_MAX%%.*}"
+  actual_max=$(awk 'NF{print $1/1000000}' OFMT="%2.2f" "$battery_path/$actual_full")
+  design_max=$(awk 'NF{print $1/1000000}' OFMT="%2.2f" "$battery_path/$design_full")
+  int_des="${design_max%%.*}"
+  int_act="${actual_max%%.*}"
 
-  if [[ "$INT_DES" -eq 0 || "$INT_ACT" -eq 0 ]]; then
-    CAP_PERCENT="0"
+  if [[ "$int_des" -eq 0 || "$int_act" -eq 0 ]]; then
+    cap_percent="0"
+    bat_health="0"
   else
-    CAP_PERCENT=$(echo "100/${DESIGN_MAX}*${ACTUAL_MAX}" | bc -l)
-    BAT_HEALTH=$(echo "$CAP_PERCENT" | awk 'NF{print $1/1}' OFMT="%2.2f")
+    cap_percent=$(echo "100/${design_max}*${actual_max}" | bc -l)
+    bat_health=$(echo "$cap_percent" | awk 'NF{print $1/1}' OFMT="%2.2f")
   fi
 
-  echo -e "\n\e[33mBattery health:\e[0m"
-  echo -e "\t\e[92mActual capacity:\e[0m $ACTUAL_MAX $UNIT"
-  echo -e "\t\e[92mDesign capacity:\e[0m $DESIGN_MAX $UNIT"
-  echo -e "\t\e[92mBattery health:\e[0m  $BAT_HEALTH%"
-  battery_condition "$CAP_PERCENT"
+  printf "\n%s%-17s%s\n" "$orange" "Battery health:" "$normal"
+  printf "\t%s%-17s%s %s %s\n" "$lightgreen" "Actual capacity:" "$normal" "$actual_max" "$unit"
+  printf "\t%s%-17s%s %s %s\n" "$lightgreen" "Design capacity:" "$normal" "$design_max" "$unit"
+  printf "\t%s%-17s%s %s%%\n" "$lightgreen" "Battery health:" "$normal" "$bat_health"
+  battery_condition "$cap_percent"
 }
 
 battery_condition() {
-  CAP_PCT="$1"
-  C_PCT="${CAP_PCT%%.*}"
-  if [ "$C_PCT" -eq 0 ]; then
-    WARN_LEVEL=0
+  local cap_pct="$1"
+  local c_pct="${cap_pct%%.*}"
+  if [[ "$c_pct" -eq 0 ]]; then
+    warn_level=0
   else
-    WARN_LEVEL=$(echo "$CAP_PCT" | awk 'NF{print $1/1}' OFMT="%.0f")
+    warn_level=$(echo "$cap_pct" | awk 'NF{print $1/1}' OFMT="%.0f")
   fi
 
-  if [ "$WARN_LEVEL" -le "0" ]; then
-    echo -e "\t\U26D4\e[31m  Replace the Battery!\e[0m \U26D4 "
-  elif [ "$WARN_LEVEL" -le "35" ]; then
-    echo -e "\t\U26D4\e[31m  The battery should be replaced.\e[0m \U26D4 "
-  elif [ "$WARN_LEVEL" -le "65" ]; then
-    echo -e "\t\U26A0\UFE0F\e[33m  The battery is getting weak.\e[0m \U26A0\UFE0F "
+  if [[ "$warn_level" -le "0" ]]; then
+    warn="\U1F4A9"
+    printf "\t%sReplace the Battery!%s  %\n" "$red" "$normal" "$warn"
+  elif [[ "$warn_level" -le "35" ]]; then
+    warn="\U1F622"
+    printf "\t%sThe battery should be replaced.%s  %\n" "$red" "$normal" "$warn"
+  elif [[ "$warn_level" -le "65" ]]; then
+    warn="\U26A0\UFE0F"
+    printf "\t%sThe battery is getting weak.%s  %\n" "$orange" "$normal" "$warn"
   else
-    echo -e "\e[32m\tThe battery is in good condition.\e[0m"
+    printf "\t%sThe battery is in good condition.%s\n" "$green" "$normal"
   fi
 }
 
-ac_status() {
-  if [ -d /sys/class/power_supply/AC ]; then
-    STATUS=$(cat /sys/class/power_supply/AC/online)
-  elif [ -d /sys/class/power_supply/ACAD ]; then
-    STATUS=$(cat /sys/class/power_supply/ACAD/online)
-  else
-    STATUS=2
-  fi
-  return "$STATUS"
+battery_specs() {
+  battery_data=$(cat "$battery_path"/uevent)
+  battery_serial=$(echo "$battery_data" | awk -F= '/SERIAL/ {print $NF}')
+  [[ -z "$battery_serial" || "$battery_serial" == " " ]] && battery_serial="Not specified"
+  printf "\n%sBattery Data:%s\n" "$orange" "$normal"
+  printf "\t%s%-15s%s%s\n" "$lightgreen" "Manufacturer:" "$normal" "$(echo "$battery_data" | awk -F= '/MANUFACTURER/ {print $NF}' | sed 's/^ //')"
+  printf "\t%s%-15s%s%s\n" "$lightgreen" "Nodel name:" "$normal" "$(echo "$battery_data" | awk -F= '/MODEL/ {print $NF}')"
+  printf "\t%s%-15s%s%s\n" "$lightgreen" "Serial number:" "$normal" "$battery_serial"
+  printf "\t%s%-15s%s%s\n" "$lightgreen" "Technology:" "$normal" "$(echo "$battery_data" | awk -F= '/TECHNOLOGY/ {print $NF}')"
+}
+
+ac_power() {
+  ac_path=$(find /sys/class/power_supply/ -name "AC*")
+  ac_status="$(cat "$ac_path/online")"
+  printf "\n%sAC Power:%s\n" "$orange" "$normal"
+  printf "\tLaptop"
+  case "$ac_status" in
+    0 )
+      printf " is not plugged in to AC power.\n"
+    ;;
+    1 )
+      printf " is plugged in to AC power.\n"
+    ;;
+    * )
+      printf "'s AC power status cannot be determined.\n"
+  esac
+}
+
+hidpp_battery() {
+  for hidpp_path in /sys/class/power_supply/hidpp_battery_?; do
+    if [[ "$hidpp_path" != "/sys/class/power_supply/hidpp_battery_?" ]]; then
+      printf "\n%sHID++ Battery:%s\n" "$orange" "$normal"
+      printf "\t%sDevice:%s %s\n" "$lightgreen" "$normal" "$(basename "$hidpp_path")"
+      printf "\t%s%s %s:%s %s%%\n" "$lightgreen" "$(cat "$hidpp_path/manufacturer")" "$(cat "$hidpp_path/model_name")" "$normal" "$(cat "$hidpp_path/capacity")"
+    fi
+  done
 }
 
 ## Execution ##
 
-clear
-if [ $# -gt 0 ]; then
+if [[ $# -gt 0 ]]; then
   case "$1" in
-    -h|--help ) help; exit ;;
-    --version ) version; exit ;;
-    * ) die "Invalid argument." 1 ;;
+    -h|--help )
+      help 0
+    ;;
+    -v|--version )
+      version
+      exit
+    ;;
+    * )
+      printf "%sInvalid argument: %s%s\n" "$lightred" "$1" "$normal" >&2
+      help 2
   esac
 fi
 
-echo -e "\e[1;33mBattery Status\e[0m"
-if [ -d /proc/acpi/button/lid/ ]; then
-  for BATTERY in /sys/class/power_supply/BAT?; do
-    if [ "$BATTERY" = "/sys/class/power_supply/BAT?" ]; then
-      echo -e "\n\e[91mNo battery detected.\e[0m"
-    else
-      echo -e "\n\e[33mBattery:\e[0m ${BATTERY##*/}"
-      battery_status
-      battery_capacity
-    fi
-  done
-  echo -e "\n\e[33mAC Power:\e[0m"
-  ac_status
-  AC_STATUS="$?"
-  echo -en "\tLaptop is "
-  case "$AC_STATUS" in
-    0 ) echo "not plugged in to AC power." ;;
-    1 ) echo "plugged in to AC power." ;;
-    * ) echo "AC power status cannot be determined." ;;
-  esac
+check_package bc
+clear
+printf "%s%sBattery Information%s\n" "$bold" "$orange" "$normal"
+if [[ -d /proc/acpi/button/lid/ ]]; then
+  battery_name=$(find /sys/class/power_supply/ -name "BAT*" | awk -F/ '/BAT/ {print $5}')
+  if [[ -n "$battery_name" ]]; then
+    battery_path="/sys/class/power_supply/$battery_name"
+    printf "\n%sBattery:%s %s\n" "$orange" "$normal" "$battery_name"
+    battery_status
+    battery_capacity
+    battery_specs
+  else
+    printf "\n%sNo battery detected%s\n" "$lightred" "$normal" >&2
+  fi
+  ac_power
+  hidpp_battery
 else
-  echo $'\n'$"This system is not a laptop."
-  echo "No battery detected."
+  printf "\nThis system is not a laptop.\n" >&2
 fi
-echo -e "\n$SCRIPT v$VERSION (Updated: $UPDATED)\n"
+
+printf "\n%s v%s (%s)\n" "$_script" "$_version" "$_updated"
 
 exit
diff --git a/check-battery b/check-battery
--- a/check-battery
+++ b/check-battery
@@ -1,146 +1,187 @@
-#!/bin/bash
+#!/usr/bin/env bash
 ###############################################################################
 # Script Name  : check-battery
 # Description  : Determine the health of a laptop battery
 # Dependencies : upower
 # Arguments    : None
-# Author       : Richard B. Romig, 30 Jul 2020
-# Email        : rick.romig@gmail.com
+# Author       : Copyright (C) 2020, Richard B. Romig, 30 Jul 2020
+# Email        : rick.romig@gmail.com | rick.romig@mymetronet.com
 # Comments     : Obtains battery data from upower utility.
 #              : Inspired by a script by Elias W (eliasw4u on Ezeetalk.com)
 # TODO (Rick)  :
-###############################################################################
-
-# Copyright (C) 2020, Richard B. Romig
+# License      : GNU General Public License, version 2.0
+# Copyright © 2023, Richard B. Romig
 # Email: rick.romig@gmail.com
-#
+# 
 # This program is free software; you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
 # the Free Software Foundation; either version 2 of the License, or
 # (at your option) any later version.
-#
+# 
 # This program is distributed in the hope that it will be useful,
 # but WITHOUT ANY WARRANTY; without even the implied warranty of
 # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 # GNU General Public License for more details.
-#
+# 
 # You should have received a copy of the GNU General Public License along
 # with this program. If not, see <https://www.gnu.org/licenses/>.
+###############################################################################
+
+## Shellcheck Directives ##
+# shellcheck source=/home/rick/bin/functionlib
+# shellcheck disable=SC1091
+
+## Load function library ##
+
+if [[ -x "$HOME/bin/functionlib" ]]; then
+  source "$HOME/bin/functionlib"
+else
+  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
+  exit 1
+fi
 
 ## Variables ##
 
-readonly SCRIPT=$(basename "$0")
-readonly VERSION="0.2.0"
-readonly UPDATED="21 Mar 2021"
+_script=$(basename "$0"); readonly _script
+readonly _version="0.4.2"
+readonly _updated="05 Oct 2023"
 
 ## Functions ##
 
 help() {
-  echo "$SCRIPT $VERSION, Upated: $UPDATED"
-  echo -e "\e[32mUsage:\e[0m $SCRIPT [option]"
-  echo -e "\e[33mOPTIONS\e[0m"
-  echo -e "$SCRIPT \t\t# displays battery health."
-  echo -e "$SCRIPT -h\t# displays this help message."
-  echo -e "$SCRIPT --help\t# displays this help message."
-  echo -e "$SCRIPT --version\t# displays the version and information about the script."
+  local errcode="${1:-2}"
+  cat <<- EOF
+  ${green}Usage:${normal} $_script [option]
+  With no argument, displays battery health information.
+  ${orange}OPTIONS:${normal}
+  -h  --help    # displays this help message.
+  -v  --version # displays the version and information about the script.
+  $_script $_version, Updated: $_updated
+EOF
+  exit "$errcode"
 }
 
 version() {
   cat <<- EOF
-  $SCRIPT $VERSION, Upated: $UPDATED
+  $_script $_version, Upated: $_updated
   Displays the charge state and health of a laptop battery using data obtained
   from the upower utilty.
 EOF
 }
 
-function die() {
-  local MSG="$1"	    # message
-  local EC=${2-1}	    # default exit status 1
-  echo -e "\n\e[91mERROR:\e[0m $MSG" >&2
-  exit "$EC"
-}
-
 cleanup() {
-  [ -f "$UPOWER_DATA" ] && rm -f "$UPOWER_DATA"
+  [[ -f "$battery_data" ]] && rm -f "$battery_data"
 }
 
 battery_status() {
-  echo -e "\n\e[33mBattery charge:\e[0m"
-  grep --color=never -E "state|to\ full|to\ empty|percentage" "$UPOWER_DATA"
+  echo $'\n'"${orange}Battery charge:${normal}"
+  grep --color=never -E "state|to\ full|to\ empty|percentage" "$battery_data"
 }
 
-battery_capacity()
-{
-  echo -e "\n\e[33mBattery health:\e[0m"
-  (grep --color=never -E "energy-full:|energy-full-design:|capacity:" "$UPOWER_DATA"
+battery_capacity() {
+  echo $'\n'"${orange}Battery health:${normal}"
+  grep --color=never -E "energy-full:|energy-full-design:|capacity:" "$battery_data"
 }
 
 warning_level() {
-  ENERGY_DES=$(awk '/energy-full-design:/ {printf "%i", $2}' "$UPOWER_DATA")
-  ENERGY_ACT=$(awk '/energy-full:/ {printf "%i", $2}' "$UPOWER_DATA")
+  energy_des=$(awk '/energy-full-design:/ {printf "%i", $2}' "$battery_data")
+  energy_act=$(awk '/energy-full:/ {printf "%i", $2}' "$battery_data")
 
-  if [[ "$ENERGY_ACT" -eq 0 || "$ENERGY_DES" -eq 0 ]]; then
-    return 0
+  if [[ "$energy_act" -eq 0 || "$energy_des" -eq 0 ]]; then
+    capacity="0"
   else
-    CAP=$(awk '/capacity/ {printf "%i", $2}' "$UPOWER_DATA")
-    return "$CAP"
+    capacity=$(awk '/capacity/ {printf "%i", $2}' "$battery_data")
   fi
+  echo "$capacity"
 }
 
 battery_condition() {
-  warning_level
-  WARN_LEVEL="$?"
-  if [ "$WARN_LEVEL" -le "0" ]; then
-    echo -e "    \U2620  \e[31mReplace the battery!\e[0m \U2620 "
-  elif [ "$WARN_LEVEL" -le "35" ]; then
-    echo -e "    \U26D4  \e[31mThe battery should be replaced.\e[0m \U26D4 "
-  elif [ "$WARN_LEVEL" -le "65" ]; then
-    echo -e "    \U26A0\UFE0F  \e[33mThe battery is getting weak.\e[0m \U26A0\UFE0F "
+  warn_level="$(warning_level)"
+  # warn_level="$?"
+  if [[ "$warn_level" -le "0" ]]; then
+    warn="\U1F4A9"
+    echo -e "    ${red}Replace the battery!${normal}  $warn"
+  elif [[ "$warn_level" -le "35" ]]; then
+    warn="\U1F622"
+    echo -e "    ${red}The battery should be replaced.${normal}  $warn"
+  elif [[ "$warn_level" -le "65" ]]; then
+    warn="\U26A0\UFE0F"
+    echo -e "    ${orange}The battery is getting weak.${normal}  $warn"
   else
-    echo -e "    \e[32mThe battery is in good condition.\e[0m"
+    echo -e "    ${green}The battery is in good condition.${normal}"
   fi
 }
 
+battery_specs() {
+  battery_serial=$(awk -F: '/serial/ {print $NF}' "$battery_data" | awk '{$1=$1}1')
+  [[ -z "$battery_serial" ]] && battery_serial="Not specified"
+  battery_tech=$(awk -F: '/technology/ {print $NF}' "$battery_data" | awk '{$1=$1}1')
+  [[ -z "$battery_tech" ]] && battery_tech="Unknown"
+  printf "\n%sBattery Data:%s\n" "$orange" "$normal"
+  printf "    %-21s%s\n" "Manufacturer:" "$(awk -F: '/vendor/ {print $NF}' "$battery_data" | awk '{$1=$1}1')"
+  printf "    %-21s%s\n" "Nodel name:" "$(awk -F: '/model/ {print $NF}' "$battery_data" | awk '{$1=$1}1')"
+  printf "    %-21s%s\n" "Serial number:" "$battery_serial"
+  printf "    %-21s%s\n" "Technology:" "$battery_tech"
+}
+
+
 ac_status() {
-  STATUS=$(/usr/bin/upower -i "$(/usr/bin/upower -e | grep 'AC')" | awk '/online:/ {print $2}')
-  echo -e "\n\e[33mAC Power:\e[0m"
+  status=$(/usr/bin/upower -i "$(/usr/bin/upower -e | grep 'AC')" | awk '/online:/ {print $NF}')
+  echo $'\n'"${orange}AC Power:${normal}"
   echo -n "    Laptop is "
-  [ "$STATUS" = "no" ] && echo -n "not "
+  [[ "$status" = "no" ]] && echo -n "not "
   echo "plugged in to AC power."
+}
+
+hidpp_battery() {
+  if /usr/bin/upower -e | grep -q mouse_hidpp_battery; then
+    hidpp_data=$(/usr/bin/upower -i "$(/usr/bin/upower -e | grep hidpp)")
+    echo $'\n'$"${orange}HID++ Battery:${normal}"
+    echo "    Device: $(echo "$hidpp_data" | awk '/native-path/ {print $NF}')"
+    echo -n "    $(echo "$hidpp_data" | awk '/model/ {print $NF}'):   "
+    echo "$hidpp_data" | awk '/percentage/ {print $NF}'
+  fi
 }
 
 ## Execution ##
 
+check_package upower
 clear
-if [ $# -gt 0 ]; then
+if [[ $# -gt 0 ]]; then
   case "$1" in
-    -h|--help ) help; exit ;;
-    --version ) version; exit ;;
-    * ) die "Invalid argument." 1 ;;
+    -h|--help )
+      help 0
+    ;;
+    -v|--version )
+      version
+      exit
+    ;;
+    * )
+    echo "${lightred}Invalid argument:${normal} $1" >&2
+    help 2
   esac
 fi
 
-echo -e "\e[1;33mBattery Status\e[0m"
-if [ -d /proc/acpi/button/lid/ ]; then
-  dpkg -l | grep -qw upower || die "Missing dependency - upower is not installed."
-  # dpkg -l | grep -qw upower || sudo apt install upower -yy"
-  BAT_NAME=$(/usr/bin/upower -e | awk -F_ '/BAT/ {print $NF}')
-  if [ -z "$BAT_NAME" ]; then
-    echo -e "\n\e[91mNo battery detected.\e[0m"
-  else
-    UPOWER_DATA=$(mktemp) || die "Failed to create temporary file." 1
+echo -e "${bold}${orange}Battery Information${normal}"
+if [[ -d /proc/acpi/button/lid/ ]]; then
+  if /usr/bin/upower -e | grep -q 'BAT'; then
+    battery_data=$(mktemp) || die "Failed to create temporary file." 1
     trap cleanup EXIT
-    /usr/bin/upower -i "$(/usr/bin/upower -e | grep BAT)" > "$UPOWER_DATA"
-    echo -e "\n\e[33mBattery:\e[0m $BAT_NAME"
+    /usr/bin/upower -i "$(/usr/bin/upower -e | grep BAT)" > "$battery_data"
+    echo $'\n'$"${orange}Battery:${normal} $(awk '/native-path:/ {print $NF}' "$battery_data")"
     battery_status
     battery_capacity
     battery_condition
-    ac_status
+    battery_specs
+  else
+    echo $'\n'"${lightred}No battery detected.${normal}" >&2
   fi
+  ac_status
+  hidpp_battery
 else
-  echo $'\n'$"This system is not a laptop. No battery detected."
+  echo $'\n'$"This system is not a laptop." >&2
 fi
 
-echo -e "\n$SCRIPT v$VERSION (Updated: $UPDATED)"
+echo $'\n'$"$_script v$_version ($_updated)"
 
 exit
diff --git a/check-updates b/check-updates
--- a/check-updates
+++ b/check-updates
@@ -1,107 +1,196 @@
-#!/bin/bash
+#!/usr/bin/env bash
 ###############################################################################
-# Script Name  : chekk-updates
-# Description  : check to see if updates are available
-# Dependencies : apt-get, select
+# Script Name  : check-updates
+# Description  : check for updates and install if necessary.
+# Dependencies : none
 # Arguments    : none
-# Author       : Richard Romig, 08 December 2018
-# Email        : rick.romig@gmail.com
-# Comments     : Lists available updates, if any.
-#              : For Debian/Ubuntu-based Linux distributions
-# Last updated : 24 Dec 2020
+# Author       : Copyright (C) 2018, Richard Romig, 08 December 2018
+# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
+# Comments     : For Debian/Ubuntu-based Linux distributions
+#              : apt-get is better suited than apt for use in scripts.
+#              : Lists available updates. Updates can be deferred.
+## TODO (rick)  :
+# License      : GNU General Public License, version 2.0
 ###############################################################################
-# Copyright (C) 2018  Richard Romig
+# Copyright © 2023, Richard B. Romig
 # Email: rick.romig@gmail.com
-#
+# 
 # This program is free software; you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
 # the Free Software Foundation; either version 2 of the License, or
 # (at your option) any later version.
-#
+# 
 # This program is distributed in the hope that it will be useful,
 # but WITHOUT ANY WARRANTY; without even the implied warranty of
-# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 # GNU General Public License for more details.
-#
+# 
 # You should have received a copy of the GNU General Public License along
 # with this program. If not, see <https://www.gnu.org/licenses/>.
 ###############################################################################
 
-# shellcheck disable=SC2034
+## Shellcheck Directives ##
+# shellcheck source=/home/rick/bin/functionlib
+# shellcheck disable=SC1091,SC2034
 
-set -e
+## Load function library ##
+
+if [[ -x "$HOME/bin/functionlib" ]]; then
+  source "$HOME/bin/functionlib"
+else
+  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
+  exit 1
+fi
+
+set -euo pipefail
+
+## Variables ##
+
+_script=$(basename "$0"); readonly _script
+readonly _version="2.0.8"
+readonly _updated="13 Oct 2023"
+
+## Functions ##
 
 install_updates() {
-  echo -e "\n\e[33mInstalling updates ...\e[0m"
+  printf "\n%sInstalling updates...%s\n" "$orange" "$normal"
   sudo apt-get dist-upgrade -yy
 }
 
 clean_cache() {
-  echo -e "\n\e[33mCleaning up apt cache ...\e[0m"
+  printf "\n%sCleaning up apt cache...%s\n" "$orange" "$normal"
   sudo apt-get autoclean
 }
 
 remove_orphans() {
-  echo -e "\n\e[33mRemoving orphaned packages ...\e[0m"
+  printf "\n%sRemoving orphaned packages...%s\n" "$orange" "$normal"
   sudo apt-get autoremove -yy
 }
 
-all_done() {
-  echo -en "\n\e[33mUpdate complete. $NUPD "
-  [ "$NUPD" -eq 1 ] && echo -n "update was" || echo -n "updates were"
-  echo -e " installed.\e[0m"
+purge_configs() {
+  local rcpkgs
+  local rcpkg
+  printf "\n%sPurging obsolete configuration files..%s\n" "$orange" "$normal"
+  rcpkgs=$(dpkg -l | awk '/^rc/ {print $2}' | wc -l)
+  if [[ "$rcpkgs" -gt 0 ]]; then
+    for rcpkg in $(dpkg -l | awk '/^rc/ {print $2}'); do
+      sudo apt-get remove --purge "$rcpkg" -yy
+    done
+  else
+    printf "No files to be purged found.\n"
+  fi
+}
+
+update_complete() {
+  local num_updates="$1"
+  printf "\n%sUpdate complete. %d" "$orange" "$num_updates"
+  (( nupd > 1 )) && printf  " updates were" || printf  " update was"
+  printf " installed.%s\n" "$normal"
 }
 
 defer_updates() {
-  echo -en "\n\e[1;33mNo updates installed. $NUPD "
-  [ "$NUPD" -eq 1 ] && echo -n "update was" || echo -n "updates were"
-  echo -e " deferred.\e[0m"
+  local num_updates="$1"
+  printf "\n%sNo updates installed. %d" "$orange" "$num_updates"
+  (( nupd > 1 )) && printf " updates were" || printf " update was"
+  printf " deferred.%s\n" "$normal"
 }
 
-format_time() {
-  ET="$1"
-  ((h=ET/3600))
-  ((m=(ET%3600)/60))
-  ((s=ET%60))
-  printf "%02d:%02d:%02d\n" $h $m $s
+update_flatpak() {
+  printf "\n%sFlatpak:%s\n" "$orange" "$normal"
+  printf "User installations...\n"
+  flatpak update --user --noninteractive --force-remove --assumeyes
+  printf "System-wide installations...\n"
+  sudo flatpak update --system --noninteractive --force-remove --assumeyes
+  printf "\n"
 }
 
-readonly SCRIPT=$(basename "$0")
-readonly VERSION="v1.3.1"
-readonly UPDATED="21 Jan 2021"
+nala_update() {
+  sudo nala upgrade
+  printf "\n%sRemoving orphaned packages...%s\n" "$orange" "$normal"
+  sudo nala autoremove
+  printf "\n%sPurging obsolete configuration files..%s\n" "$orange" "$normal"
+  sudo nala autopurge
+  printf "\n"
+}
+
+apt_update() {
+  local nupd
+  sudo apt-get update
+  # Get number of packages that can be upgraded
+  nupd=$(apt-get -s dist-upgrade | grep "^[[:digit:]]\+ upgraded" | cut -d' ' -f1)
+  # If there are packages to be upgraded
+  if (( nupd > 0 )); then
+    printf "%s%d " "$orange" "$nupd"
+    (( nupd > 1 )) && printf "packages" || printf "package"
+    printf " can be upgraded%s.\n" "$normal"
+    # List upgradeable packages
+    apt list --upgradeable
+    # Options menu
+    COLUMNS=40
+    printf "\n%s%sUpdate options:%s\n" "$underline" "$green" "$normal"
+    PS3="Choose an option: "
+    options=("Install updates." "Install updates & clean cache" "Install updates & remove orphaned packages." \
+    "Install updates, clean cache, & remove orphaned packages." "Defer updates until later.")
+    select opt in "${options[@]}"; do
+      case $REPLY in
+        1 )
+          install_updates
+          update_complete "$nupd"
+          break
+        ;;
+        2 )
+          install_updates
+          clean_cache
+          update_complete "$nupd"
+          break
+        ;;
+        3 )
+          install_updates
+          remove_orphans
+          purge_configs
+          update_complete "$nupd"
+          break
+        ;;
+        4 )
+          install_updates
+          clean_cache
+          remove_orphans
+          purge_configs
+          update_complete "$nupd"
+          break
+        ;;
+        5 )
+          defer_updates "$nupd"
+          break
+        ;;
+        * )
+          printf "%sInvalid option!%s Select 1..5\n" "$lightred" "$normal" >&2
+      esac
+    done
+  else
+    printf "\n%sAll packages are up to date.%s\n" "$orange" "$normal"
+  fi
+}
+
+## Execution ##
+
+user_in_sudo
 
 SECONDS=0
 
 clear
-echo -e "\e[1;33m$SCRIPT $VERSION ($UPDATED)\e[0m"
-echo "Licensed under the GNU General Public License, version 2.0"
-echo -e "\e[1;33mChecking for updates on $LHOST...\e[0m"
+printf "%s%s%s v%s (%s)\n" "$bold" "$orange" "$_script" "$_version" "$_updated"
+printf "System: %s (# %s)\n" "$(uname -n)" "$(local_ip)"
+printf "Distro: %s\n" "$(get_distribution)"
+printf "Kernel: %s\n\n" "$(uname -sr)"
+printf "Checking for updates...%s\n\n" "$normal"
 
-sudo apt-get update
-
-NUPD=$(apt-get upgrade -s 2>/dev/null | grep -P '^\d+ upgraded' | cut -d" " -f1)
-
-if [ "$NUPD" -gt 0 ]; then
-  echo -en "\e[33m$NUPD "
-  (( NUPD > 1 )) && echo -n "packages" || echo -n "package"
-  echo " can be upgraded.${normal}"
-  apt list --upgradeable
-  echo -e "\n\e[4;33mUpdate options:\e[0m"
-  PS3="Choose an option: "
-  OPTIONS=("Install updates." "Install updates, remove orphaned packages, & clean cache." \
-   "Install updates & remove orphaned packages" "Defer updates until later.")
-  select OPT in "${OPTIONS[@]}"
-  do
-    case $REPLY in
-      1 ) install_updates; all_done; break ;;
-      2 ) install_updates; remove_orphans; clean_cache; all_done; break ;;
-      3 ) install_updates; remove_orphans; all_done; break ;;
-      4 ) defer_updates; break ;;
-      * ) echo -e "\e[91mInvalid option!\e[0m Select 1..4" >&2 ;;
-    esac
-  done
+if exists nala; then
+  nala_update
 else
-  echo -e "\n\e[33mAll packages are up to date.\e[0m"
+  apt_update
 fi
-echo "Script completed in $(format_time $SECONDS)"
-exit
+
+exists flatpak && update_flatpak
+
+leave "Script completed in $(format_time $SECONDS)"
diff --git a/ip-info b/ip-info
--- a/ip-info
+++ b/ip-info
@@ -1,111 +1,214 @@
-#!/bin/bash
+#!/usr/bin/env bash
 #####################################################################
 # Script Name  : ip-info
-# Description  : Displays IP information
-# Dependencies : awk, ip, iw, iwgetid, nmcli, wget
+# Description  : Displays IP & network device information
+# Dependencies : curl, iw, network-manager (nmcli)
 # Arguments    : None
-# Author       : Richard Romig, 19 February 2019
-# Email        : rick.romig@gmail.com
-# Comment      : iwconfig may not show signal level for some wireless cards,
-#              : noteably, Broadcom cards. See man iwconfig.
+# Author       : Copyright (C) 2019, Richard Romig, 19 February 2019
+# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
+# Comments     : hp-2560p (#23) requires sudo for the following command:
+#              : awk '/wl/ {print $4 " dBm"}' /proc/net/wireless | sed 's/\.//'
 # TODO (rick)  :
-###############################################################################
-
-# Copyright (C) 2019, Richard B. Romig
+# License      : GNU General Public License, version 2.0
+#####################################################################
+# Copyright © 2023, Richard B. Romig
 # Email: rick.romig@gmail.com
-#
+# 
 # This program is free software; you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
 # the Free Software Foundation; either version 2 of the License, or
 # (at your option) any later version.
-#
+# 
 # This program is distributed in the hope that it will be useful,
 # but WITHOUT ANY WARRANTY; without even the implied warranty of
-# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 # GNU General Public License for more details.
-#
+# 
 # You should have received a copy of the GNU General Public License along
 # with this program. If not, see <https://www.gnu.org/licenses/>.
+#####################################################################
+
+## Shellcheck Directives ##
+# shellcheck source=/home/rick/bin/functionlib
+# shellcheck disable=SC1091,SC2317
+
+## Load function library ##
+
+if [[ -x "$HOME/bin/functionlib" ]]; then
+  source "$HOME/bin/functionlib"
+else
+  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
+  exit 1
+fi
 
 ## Functions ##
 
-main()
-{
-  SCRIPT=$(basename "$0")
-  VERSION="2.2.0"
-  UPDATED="26 Sep 2020"
+req_sudo() {
+  lhost="${HOSTNAME:-$(hostname)}"
+  case "$lhost" in
+    hp-2560p )
+      return "$TRUE" 
+    ;;
+    * )
+      return "$FALSE"
+  esac
+}
+
+show_public() {
+  public_ipv4=$(/usr/bin/curl -s ifconfig.me)     # http://ident.me
+  [[ -n "$public_ipv4" ]] && echo -e "\t${darkgray}IPv4:${normal} $public_ipv4" || echo -e "\tNo public IPv4 address found."
+  # public_ipv6=$(/usr/bin/curl -s ifconfig.co)
+  # [[ -n "$public_ipv6" ]] && echo -e "\t${lightgreen}IPv6:${normal} $public_ipv6" || echo -e "\tNo public IPv6 address found."
+}
+
+show_wired() {
+  eth_int=$(/usr/bin/nmcli dev | awk '/ethernet/ {print $1}')
+  if [[ -n "$eth_int" ]]; then
+    eth_state=$(cat "/sys/class/net/$eth_int/operstate")
+    eth_ip=$(/usr/bin/nmcli dev show "$eth_int" | awk '/IP4.ADDRESS/ {print $NF}')
+    eth_mac=$(/usr/bin/nmcli dev show "$eth_int" | awk '/GENERAL.HWADDR/ {print $NF}')
+  fi
+
+  echo -en "\t${darkgray}Ethernet:${normal} "
+  case "$eth_state" in
+    up )
+      echo "$eth_ip"
+      echo -e "\t  ${gray}Device:${normal} $eth_int"
+      echo -e "\t     ${gray}MAC:${normal} $eth_mac"
+    ;;
+    down )
+      echo "Not connected"
+      echo -e "\t  ${gray}Device:${normal} $eth_int"
+      echo -e "\t     ${gray}MAC:${normal} $eth_mac"
+    ;;
+    unknown )
+      echo "Unknown state"
+      echo -e "\t  ${gray}Device:${normal} $eth_int"
+      echo -e "\t     ${gray}MAC:${normal} $eth_mac"
+    ;;
+    * )
+      echo "No device found."
+  esac
+}
+
+show_wireless() {
+  wifi_int=$(/usr/bin/nmcli dev | awk '/wifi/ {print $1;exit}')
+  if [[ -n "$wifi_int" ]]; then
+    wifi_state=$(cat "/sys/class/net/$wifi_int/operstate")
+    wifi_ip=$(/usr/bin/nmcli dev show "$wifi_int" | awk '/IP4.ADDRESS/ {print $NF}')
+    wifi_mac=$(/usr/bin/nmcli dev show "$wifi_int" | awk '/GENERAL.HWADDR/ {print $NF}')
+    if req_sudo; then
+      wifi_ssid=$(sudo /sbin/iw dev "$wifi_int" link | awk '/SSID/ {print $2}')
+      wifi_sig=$(sudo /sbin/iw dev "$wifi_int" link | awk '/signal/ {print $2,$3}')
+    else
+      wifi_ssid=$(/sbin/iw dev "$wifi_int" link | awk '/SSID/ {print $2}')
+      wifi_sig=$(/sbin/iw dev "$wifi_int" link | awk '/signal/ {print $2,$3}')
+    fi
+    [[ -z "$wifi_ssid" ]] && wifi_ssid="Not available"
+    [[ -z "$wifi_sig" ]] && wifi_sig="Not available"
+  fi
+
+  echo -en "\t${darkgray}Wireless:${normal} "
+  case "$wifi_state" in
+    up )
+      echo "$wifi_ip"
+      echo -e "\t  ${gray}Device:${normal} $wifi_int"
+      echo -e "\t     ${gray}MAC:${normal} $wifi_mac"
+      echo -e "\t    ${gray}SSID:${normal} $wifi_ssid"
+      echo -e "\t  ${gray}Signal:${normal} $wifi_sig"
+    ;;
+    down )
+      echo "Not connected"
+      echo -e "\t  ${gray}Device:${normal} $wifi_int"
+      echo -e "\t     ${gray}MAC:${normal} $wifi_mac"
+    ;;
+    unknown )
+      echo "Unknown state"
+      echo -e "\t  ${gray}Device:${normal} $wifi_int"
+      echo -e "\t     ${gray}MAC:${normal} $wifi_mac"
+    ;;
+    * )
+      echo "No device found."
+  esac
+}
+
+show_bridge() {
+	# br_int=$(/usr/bin/nmcli dev | awk '/bridge/ {print $1}')
+  br_int=$(ip ad show | awk '/: vir/ {print $2;exit}' | sed 's/:$//')
+
+	if [[ -n "$br_int" ]]; then
+    br_state=$(cat "/sys/class/net/$br_int/operstate")
+	  # br_ip=$(/usr/bin/nmcli dev show "$br_int" | awk '/IP4.ADDRESS/ {print $NF}')
+    br_ip=$(ip addr show | awk '/vir/ && /brd/ {print $2}')
+	  # br_mac=$(/usr/bin/nmcli dev show "$br_int" | awk '/GENERAL.HWADDR/ {print $NF}')
+    br_mac=$(cat "/sys/class/net/$br_int/address")
+	  # br_route=$(/usr/bin/nmcli dev show "$br_int" | awk '/IP4.ROUTE/ {print $4;exit}'| sed 's/,//')
+    br_route=$(ip route show | awk '/vir/ && /kernel/ {print $1}')
+
+    echo -en "\t${darkgray}Bridge:${normal} "
+    case "$br_state" in
+      up )
+        echo -e "\t${darkgray}Bridge:${normal}\t$br_ip"
+        echo -e "\t${gray}Device:${normal} $br_int"
+        echo -e "\t   ${gray}MAC:${normal} $br_mac"
+	      echo -e "\t${gray}Subnet:${normal} $br_route"
+      ;;
+      down )
+        echo "Not connected"
+        echo -e "\t${gray}Device:${normal} $br_int"
+        echo -e "\t   ${gray}MAC:${normal} $br_mac"
+      ;;
+      unknown )
+        echo "Unknown state"
+        echo -e "\t${gray}Device:${normal} $br_int"
+        echo -e "\t   ${gray}MAC:${normal} $br_mac"
+      ;;
+      * )
+        echo "No device found."
+    esac
+	fi
+}
+
+show_gateway() {
+  echo "${orange}Default Gateway:${normal}"
+  /sbin/ip route | awk '/default/ {print "\t"$3}' | sort -u
+}
+
+show_dns() {
+  echo "${orange}DNS Servers:${normal}"
+  /usr/bin/nmcli dev show | awk '/IP4.DNS/ {print "\t"$NF}' | sort -u
+}
+
+check_dependencies() {
+  local packages=( curl iw network-manager )
+  check_packages "${packages[@]}"
+}
+
+main() {
+  local _script; _script=$(basename "$0")
+  local _version="2.6.5"
+  local _updated="15 Sep 2023"
+
+  req_sudo && user_in_sudo
+
+  check_dependencies
 
   clear
-  echo -e "\n\e[93mIP Information\e[0m"
-  echo -e "\e[93m==============\e[0m\n"
-  echo -e "\e[32mPublic IP:\e[0m"
+  echo "${lightyellow}"
+  box "IP Information - $(uname -n)" "*"
+  echo "${normal}"
+  echo "${orange}Public IP:${normal}"
   show_public
-  echo -e "\e[32mLocal IP:\e[0m"
+  echo "${orange}Local IP:${normal}"
   show_wired
   show_wireless
-  show_gateway_dns
-  echo $'\n'$"$SCRIPT v$VERSION (Updated: $UPDATED)"
-  exit
-}
-
-show_public()
-{
-  PUBLIC_IP=$(/usr/bin/wget -qO- http://ipv4.icanhazip.com)
-
-  if [ -n "$PUBLIC_IP" ]; then
-    echo -e "\t$PUBLIC_IP"
-  else
-    echo -e "\tNo Internet address found."
-  fi
-}
-
-show_wired()
-{
-  ETH_INT=$(/usr/bin/nmcli dev | awk '/ethernet/ {print $1}')
-
-  [ -n "$ETH_INT" ] && ETH_IP=$(/sbin/ip -o -4 addr show \
-  | awk -v name="$ETH_INT" '$0~name {print $4" ("$2")"}')
-
-  echo -en "\t\e[92mEthernet:\e[0m "
-  if [ -n "$ETH_INT" ] && [ -n "$ETH_IP" ]; then
-    echo "$ETH_IP"
-  elif [ -n "$ETH_INT" ]; then
-    echo "Not connected"
-  else
-    echo "No device found."
-  fi
-}
-
-show_wireless()
-{
-  WIFI_INT=$(/usr/bin/nmcli dev | awk '/wifi/ {print $1}')
-
-  if [ -n "$WIFI_INT" ]; then
-    WIFI_IP=$(/sbin/ip -o -4 addr show | awk -v name="$WIFI_INT" '$0~name {print $4" ("$2")"}')
-    WIFI_SIG="$(/sbin/iw "$WIFI_INT" station dump | awk '/signal:/ {print $2,$3;exit}')"
-    [ -z "$WIFI_SIG" ] && WIFI_SIG="Not available"
-  fi
-
-  echo -en "\t\e[92mWireless:\e[0m "
-  if [ -n "$WIFI_INT" ] && [ -n "$WIFI_IP" ]; then
-    echo "$WIFI_IP"
-    echo -e "\t    \e[92mSSID:\e[0m $(/sbin/iwgetid -r)"
-    echo -e "\t  \e[92mSignal:\e[0m $WIFI_SIG"
-  elif [ -n "$WIFI_INT" ]; then
-    echo "Not connected"
-  else
-    echo "No device found."
-  fi
-}
-
-show_gateway_dns()
-{
-  echo -e "\e[32mDefault Gateway:\e[0m"
-  /sbin/ip route | awk '/default/ {print "\t"$5": "$3}'
-  echo -e "\e[32mDNS Servers:\e[0m"
-  /usr/bin/nmcli dev show | awk '/IP4.DNS/ {printf "\t%s\n",$2}'
+  # show_bridge
+  show_gateway
+  show_dns
+  echo ""
+  leave "$_script v$_version ($_updated)"
 }
 
 ## Execution ##
 
-main "$0"
+main
diff --git a/ren-ext b/ren-ext
--- a/ren-ext
+++ b/ren-ext
@@ -1,120 +1,114 @@
-#!/bin/bash
+#!/usr/bin/env bash
 ###############################################################################
 # Script Name  : ren-ext
 # Description  : Renames file extensions in the current directory
-# Dependencies : rename, shopt
+# Dependencies : none
 # Arguments    : File extenstion to be changed
-# Author       : Richard Romig
+# Author       : Copyright (C) 2017, Richard Romig
 # Email        : rick.romig@gmail.com
-# Comment      : File extensions are case insensitive
+# Comment      : File extensions are not case sensitive
+# License      : GNU General Public License, version 2.0
 ###############################################################################
-# Copyright (C) 2018  Richard Romig
+
+# Copyright © 2023, Richard B. Romig
 # Email: rick.romig@gmail.com
-#
+# 
 # This program is free software; you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
 # the Free Software Foundation; either version 2 of the License, or
 # (at your option) any later version.
-#
+# 
 # This program is distributed in the hope that it will be useful,
 # but WITHOUT ANY WARRANTY; without even the implied warranty of
-# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 # GNU General Public License for more details.
-#
+# 
 # You should have received a copy of the GNU General Public License along
 # with this program. If not, see <https://www.gnu.org/licenses/>.
-###############################################################################
 
-usage()
-{
-  echo "Usage: $SCRIPT extension"
-  echo "Example: $SCRIPT JPG"
-  echo "Supported extensions: AVI, BAK, FLV, GIF, HTM, HTML, JPEG, JPG, MP3,"
-  echo " MP4, MPG, MPEG, PDF, PNG, TXT, WMV"
-  echo "Input file extensions are case insensitive. Any combination of upper and"
-  echo "lower case are acceptable. Changed file extensions will be lowercase."
-  exit 1
+## Variables ##
+
+_script=$(basename "$0"); readonly _script
+readonly _version="2.0.5"
+readonly _updated="05 Feb 2023"
+
+## Functions ##
+
+usage() {
+  local errcode="${1:-2}"
+  cat << EOF
+Usage: $SCRIPT extension
+Example: $SCRIPT JPG
+Supported extensions: AVI, BAK, FLV, GIF, HTM, HTML, JPEG, JPG, MP3,
+MP4, MPG, MPEG, PDF, PNG, TXT, WMV
+Input file extensions are not case sensitive. Any combination of upper and
+lower case are acceptable. Changed file extensions will be lowercase.
+EOF
+  exit "$errcode"
 }
 
-SCRIPT=$(basename "$0")
-VERSION="2.0.3"
-UPDATED="15 Jun 2020"
+## Execution ##
 
-echo "$SCRIPT v$VERSION (Updated: $UPDATED)"
+echo "$_script v$_version ($_updated)"
 echo "Bulk renames file extensions in the current diectory."
-echo -e "Copyright 2018, Richard Romig\n"
+echo -e "Copyright 2018-2022, Richard Romig\n"
 
 # Check for arguments
 
-if [ -z "$1"  ]; then
-  echo -e "\e[1;31mERROR:\e[0m Must provide a file extension to be renamed." <&2
-  usage
+if [[ "$#" -eq 0 ]]; then
+  echo -e "\e[91mERROR:\e[0m Must provide a file extension to be renamed." <&2
+  usage 2
 else
-  EXT="$1"
+  ext="$1"
 fi
 
-# Rename file extenssions based on the passed argument
+# Rename file extensions based on the passed argument
 
 shopt -s nocasematch
-case $EXT in
+case $ext in
   avi)
-    echo "Renaming .$EXT files to .avi"
-    rename -v 's/\.AVI$/\.avi/i' ./*
-    ;;
+    echo "Renaming .$ext files to .avi"
+    rename -v 's/\.AVI$/\.avi/i' ./* ;;
   bak)
-    echo "Renaming .$EXT files to .bak"
-    rename -v 's/\.BAK$/\.bak/i' ./*
-    ;;
+    echo "Renaming .$ext files to .bak"
+    rename -v 's/\.BAK$/\.bak/i' ./* ;;
   flv)
-    echo "Renaming .$EXT files to .flv"
-    rename -v 's/\.FLV$/\.flv/i' ./*
-    ;;
+    echo "Renaming .$ext files to .flv"
+    rename -v 's/\.FLV$/\.flv/i' ./* ;;
   gif)
-    echo "Renaming .$EXT files to .gif"
-    rename -v 's/\.GIF$/\.gif/i' ./*
-    ;;
+    echo "Renaming .$ext files to .gif"
+    rename -v 's/\.GIF$/\.gif/i' ./* ;;
   htm|html)
-    echo "Renaming .$EXT files to .html"
-    rename -v 's/\.HTML?$/\.html/i' ./*
-    ;;
+    echo "Renaming .$ext files to .html"
+    rename -v 's/\.HTML?$/\.html/i' ./* ;;
   jpeg|jpg)
-    echo "Renaming .$EXT files to .jpg"
-    rename -v 's/\.JPE?G$/\.jpg/i' ./*
-    ;;
+    echo "Renaming .$ext files to .jpg"
+    rename -v 's/\.JPE?G$/\.jpg/i' ./* ;;
   mp3)
-    echo "Renaming .$EXT files to .mp3"
-    rename -v 's/\.MP3$/\.mp3/i' ./*
-    ;;
+    echo "Renaming .$ext files to .mp3"
+    rename -v 's/\.MP3$/\.mp3/i' ./* ;;
   mp4)
-    echo "Renaming .$EXT files to .mp4"
-    rename -v 's/\.MP4$/\.mp4/i' ./*
-    ;;
+    echo "Renaming .$ext files to .mp4"
+    rename -v 's/\.MP4$/\.mp4/i' ./* ;;
   mpg|mpeg)
-    echo "Renaming .$EXT files to .mpg"
-    rename -v 's/\.MPE?G$/\.mpg/i' ./*
-    ;;
+    echo "Renaming .$ext files to .mpg"
+    rename -v 's/\.MPE?G$/\.mpg/i' ./* ;;
   pdf)
-    echo "Renaming .$EXT files to .pdf"
-    rename -v 's/\.PDF$/\.pdf/i' ./*
-    ;;
+    echo "Renaming .$ext files to .pdf"
+    rename -v 's/\.PDF$/\.pdf/i' ./* ;;
   png)
-    echo "Renaming .$EXT files to .png"
-    rename -v 's/\.PNG$/\.png/i' ./*
-    ;;
+    echo "Renaming .$ext files to .png"
+    rename -v 's/\.PNG$/\.png/i' ./* ;;
   txt)
-    echo "Renaming .$EXT files to .txt"
-    rename -v 's/\.TXT$/\.txt/i' ./*
-    ;;
+    echo "Renaming .$ext files to .txt"
+    rename -v 's/\.TXT$/\.txt/i' ./* ;;
   wmv)
-    echo "Renaming .$EXT files to .wmv"
-    rename -v 's/\.WMV$/\.wmv/i' ./*
-    ;;
+    echo "Renaming .$ext files to .wmv"
+    rename -v 's/\.WMV$/\.wmv/i' ./* ;;
   *)
-    echo -e "\e[1;31mERROR:\e[0m .$EXT is NOT a supported file extension."
-    usage
-    ;;
+    echo -e "\e[1;31mERROR:\e[0m .$ext is NOT a supported file extension."
+    usage 1 ;;
 esac
-
 shopt -u nocasematch
 
 exit
diff --git a/rename-host b/rename-host
--- a/rename-host
+++ b/rename-host
@@ -1,106 +1,116 @@
-#!/bin/bash
+#!/usr/bin/env bash
 #############################################################################
 # Script Name  : rename-host
 # Description  : Changes the system hostname
-# Dependencies : awk, sed
+# Dependencies : None
 # Arguments    : None
-# Author       : Richard B. Romig, 06 Nov 2019
-# Email        : rick.romig@gmail.com
-# Comments     : Hostname is changed in both /etc/hostname and /etc/hosts.
-# Hostname length limited to 15 characters for NETBIOS compatibility.
+# Author       : Copyright (C) 2019, Richard B. Romig, 06 Nov 2019
+# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
+# Comments     : Changes the hostname in both /etc/hostname and /etc/hosts.
+#              : antiX/MX Linux: /etc/hosts - 127.0.0.1      hostname
+#              : Rules based on hostname(7) man page
+#              : Hostname length limited to 15 characters for NETBIOS compatibility.
+# TODO (Rick)  :
+# License      : GNU General Public License, version 2.0
 #############################################################################
-# Copyright (C) 2020, Richard B. Romig
+
+# Copyright © 2023, Richard B. Romig
 # Email: rick.romig@gmail.com
-#
+# 
 # This program is free software; you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
 # the Free Software Foundation; either version 2 of the License, or
 # (at your option) any later version.
-#
+# 
 # This program is distributed in the hope that it will be useful,
 # but WITHOUT ANY WARRANTY; without even the implied warranty of
 # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 # GNU General Public License for more details.
-#
+# 
 # You should have received a copy of the GNU General Public License along
 # with this program. If not, see <https://www.gnu.org/licenses/>.
 
+## Shellcheck Directives ##
+# shellcheck source=/home/rick/bin/functionlib
+# shellcheck disable=SC1091
+
+## Load function library ##
+
+if [[ -x "$HOME/bin/functionlib" ]]; then
+  source "$HOME/bin/functionlib"
+else
+  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
+  exit 1
+fi
+
 ## Variables ##
 
-readonly SCRIPT=$(basename "$0")
-readonly VERSION="2.1.3"
-readonly UPDATED="24 Dec 2020"
-readonly OLDHOST=$HOSTNAME
+_script=$(basename "$0"); readonly _script
+readonly _version="0.4.3"
+readonly _updated="23 May 2023"
+readonly old_host="${HOSTNAME:-$(hostname)}"
 
 ## Functions ##
 
-leave() {
-  local MSG="$1"
-
-  if [ -z "$MSG" ]; then
-    echo "Exiting the script."
-  else
-    echo "$MSG"
-  fi
-  exit
-}
-
 name_rules() {
-  echo -e "\e[31mHostname Rules\e[0m"
-  echo -e "\e[33m*\e[0m 5-15 characters"
-  echo -e "\e[33m*\e[0m a-z, 0-9, - (hyphen)"
-  echo -e "\e[33m*\e[0m lowercase (uppercase will be converted)"
-  echo -e "\e[33m*\e[0m no special characters"
-  echo -e "\e[33m*\e[0m first character cannot be a hyphen or a digit"
-  echo -e "\e[33m*\e[0m last character cannot be a hyphen"
+  cat << EOF
+${red}Hostname Rules${normal}
+  ${orange}*${normal} 5-15 characters (for NETBIOS compatibility)
+  ${orange}*${normal} a-z, 0-9, - (hyphen)
+  ${orange}*${normal} lowercase (uppercase will be converted)
+  ${orange}*${normal} no special characters
+  ${orange}*${normal} first character cannot be a hyphen or a digit
+  ${orange}*${normal} last character cannot be a hyphen
+EOF
 }
 
 ## Execution ##
 
 # Enter new hostname and check rules
 
-while true
-do
+while true; do
   clear
-  echo "$SCRIPT v$VERSION (Updated: $UPDATED)"
-  echo "Licensed under the GNU General Public License, version 2.0"
+  echo "$_script v$_version ($_updated)"
   echo "Renames the system hostname."
   name_rules
-  echo -e "\nCurrent hostname is $OLDHOST\n"
+  echo -e "\nCurrent hostname is $old_host\n"
 
-  read -rp "Enter new hostname: " NEWHOST
-  STRLEN=${#NEWHOST}
-  if [ "$STRLEN" -lt 5 ] || [ "$STRLEN" -gt 15 ]; then
-    echo $'\n'$"Invalid length" >&2
+  read -rp "Enter new hostname: " new_host
+  strlen=${#new_host}
+  if [[ "$strlen" -lt 5 || "$strlen" -gt 15 ]]; then
+    echo $'\n'$"${lightred}Invalid length${normal}" >&2
     name_rules
     continue
   fi
-  case $NEWHOST in
+  # Check new hostname against the rules
+  case "$new_host" in
     -* )
-      echo $'\n'$"Cannot start with a hypen" >&2
+      echo $'\n'$"${lightred}Cannot start with a hypen${normal}" >&2
       name_rules
       continue
-      ;;
+    ;;
     *- )
-      echo $'\n'$"Cannot end with a hyphen" >&2
+      echo $'\n'$"${lightred}Cannot end with a hyphen${normal}" >&2
       name_rules
-      continue ;;
+      continue
+    ;;
     [0-9]* )
-      echo $'\n'$"Cannot start with a digit" >&2
-      name_rules;
+      echo $'\n'$"${lightred}Cannot start with a digit${normal}" >&2
+      name_rules
       continue
-      ;;
+    ;;
     *[^a-zA-Z0-9-]* )
-      echo $'\n'$"Cannot contain special characters" >&2
-      name_rules;
+      echo $'\n'$"${lightred}Cannot contain special characters${normal}" >&2
+      name_rules
       continue
-      ;;
+    ;;
     * )
-      ;;
+      echo $'\n'$"${green}New hostname is valid.$(normal)"
   esac
-  NEWHOST=$(echo "$NEWHOST" | awk '{print tolower($0)}')
-  if [ "$NEWHOST" == "$OLDHOST" ]; then
-    echo "Hostnames are the same." >&2
+  # Compare new hostname with the old hostname
+  new_host="${new_host,,}"
+  if [[ "$new_host" == "$old_host" ]]; then
+    echo "${lightred}Hostnames are the same.${normal}" >&2
     name_rules
     continue
   else
@@ -108,24 +118,30 @@ do
   fi
 done
 
-# Make backups of old files and change hostnames
+# Checking for sudo privileges...
+user_in_sudo
 
-sudo ls > /dev/null 2>&1
-echo $'\n'$"Changing the hostname from $OLDHOST to $NEWHOST ..."
-cp -p /etc/hostname /etc/hostname.old > /dev/null 2>&1
-cp -p /etc/hosts /etc/hosts.old > /dev/null 2>&1
-sudo sed -i "s/$OLDHOST/$NEWHOST/" /etc/hostname
-sudo sed -i "s/$OLDHOST/$NEWHOST/" /etc/hosts
+echo $'\n'$"Changing the hostname from $old_host to $new_host ..."
+# Make backup copies of the original files and replace old hostname with new hostname
+sudo sed -i.old "s/$old_host/$new_host/" /etc/hostname
+sudo sed -i.old "s/$old_host/$new_host/" /etc/hosts
 
 # Confirm changes
 
-HOST1=$(cat /etc/hostname)
-HOST2=$(awk '/127.0.1.1/ {print $2}' /etc/hosts)
-[ -z "$HOST2" ] && HOST2=$(grep -m2 '127.0.0.1' /etc/hosts | tail -n1 | awk '{print $2}')
-echo -e "/etc/hostname = $HOST1\t/etc/hosts = $HOST2"
-if [ "$HOST1" == "$NEWHOST" ] && [ "$HOST2" == "$NEWHOST" ]; then
-  leave "Hostname successfully changed."
+host1=$(cat /etc/hostname)
+host2=$(awk '/127.0.1.1/ {print $2}' /etc/hosts)
+if [[ -z "$host2" ]]; then
+# Change address for hostname from 127.0.0.1 to 127.0.1.1
+  host2=$(awk '/127.0.0.1/ {print $2}' /etc/hosts | tail -n1)
+  sudo sed -i '0,/127.0.0.1/! {0,/127.0.0.1/ s/127.0.0.1/127.0.1.1/}' /etc/hosts
+fi
+echo -e "/etc/hostname = $host1\t/etc/hosts = $host2"
+if [[ "$host1" == "$new_host" && "$host2" == "$new_host" ]]; then
+  # Remove the original hostname and hosts files
+  sudo rm /etc/hostname.old /etc/hosts.old
+  leave "Hostname successfully changed. Reboot to ensure the change takes effect."
 else
+  # Revert to the hold hostname
   sudo mv /etc/hostname.old /etc/hostname > /dev/null 2>&1
   sudo mv /etc/hosts.old /etc/hosts > /dev/null 2>&1
   leave "Hostname change was unsuccessful. Reverted to the original hostname."
diff --git a/system-info b/system-info
--- a/system-info
+++ b/system-info
@@ -1,130 +1,276 @@
-#!/bin/bash
-###############################################################################
+#!/usr/bin/env bash
+##########################################################################
 # Script Name  : system-info
-# Description  : Gathers system information to a file in home directory
-# Dependencies : apt, awk, cut, date, dmidecode, df, dpkg, free, grep, hdpram,
-#              : lsblk, lsb_release, lscpu, lspci, nmcli, sed, tee, tune2fs uname
-# Arguments    : None
-# Author       : Richard Romig
-# Email        : rick.romig@gmail.com
-# Comments     : Requires root/sudo privileges
-# dmidecode may produce error messages in some systems. They can be
-# safely ignored and removed from the file with any text editor.
-# hdparm may display extraneous info which can be removed in a text editor.
-# lsblk may incorrectly display the home partition, if timeshift was installed
-# and configured to save snapshots to the /home. This may be edited.
-# Last Updated : 04 Feb 2021
-###############################################################################
-# Copyright (C) 2018  Richard Romig
+# Description  : Gathers system information and writes to a file in home directory
+# Dependencies : dmidecode, hdparm, lshw, tune2fs, nvme-cli
+# Arguments    : none
+# Author       : Copyright (C) 2022, Richard B. Romig, 15 Jul 2022
+# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
+# Comments     : Rewrite of version 2.5.0
+# TODO (Rick)  :
+# License      : GNU General Public License, version 2.0
+##########################################################################
+
+# Copyright © 2023, Richard B. Romig
 # Email: rick.romig@gmail.com
-#
+# 
 # This program is free software; you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
 # the Free Software Foundation; either version 2 of the License, or
 # (at your option) any later version.
-#
+# 
 # This program is distributed in the hope that it will be useful,
 # but WITHOUT ANY WARRANTY; without even the implied warranty of
-# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 # GNU General Public License for more details.
-#
+# 
 # You should have received a copy of the GNU General Public License along
 # with this program. If not, see <https://www.gnu.org/licenses/>.
-###############################################################################
 
-sudo ls > /dev/null 2>&1
+## Shellcheck Directives ##
+# shellcheck source=/home/rick/bin/functionlib
+# shellcheck disable=SC1091,SC2034
 
-# hdparm needed to extract hard drive information
+## Source function library ##
 
-dpkg -l | grep -qw hdparm || sudo apt install hdparm -yyq
-dpkg -l | grep -qw upower || sudo apt install upower -yyq   # laptop battery
+if [[ -x "$HOME/bin/functionlib" ]]; then
+  source "$HOME/bin/functionlib"
+else
+  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
+  exit 1
+fi
 
-# Base variables
+## Variables ##
 
-HOMEDIR=$HOME
-LHOST=$(/bin/uname -n)
-INFOFILE="$HOMEDIR/$LHOST.info"
-TODAY=$(date +"%d %B %Y")
-VERSION="v 2.1.8"
+_script=$(basename "$0"); readonly _script
+readonly _version="3.4.0"
+readonly _updated="05 Oct 2023"
+readonly lhost="${HOSTNAME:-$(hostname)}"
+readonly info_file="$HOME/$lhost.info"
+today=$(date +'%d %B %Y'); readonly today
 
-# Computer information
+## Functions ##
 
-MFGNAME=$(sudo /usr/sbin/dmidecode -s system-manufacturer 2>/dev/null)
-PRODNAME=$(sudo /usr/sbin/dmidecode -s system-product-name 2>/dev/null)
-VERNAME=$(sudo /usr/sbin/dmidecode -s system-version 2>/dev/null)
-SERNUM=$(sudo /usr/sbin/dmidecode -s system-serial-number 2>/dev/null)
+check_dependencies() {
+  check_package "lshw"
+  [[ -b /dev/sda ]] && check_package hdparm
+  [[ -c /dev/nvme0 ]] && check_package nvme-cli
+}
 
-# Operating system
+cleanup() {
+  [[ -f "$tmp_file" ]] && rm -f "$tmp_file"
+  [[ -f "$hd_data" ]] && rm -f "$hd_data"
+}
 
-OSNAME=$(/bin/uname -o)
-DISTRO=$(/usr/bin/lsb_release -d | cut -f2)
-ROOTDEV=$(/bin/df -P / | tail -1 | cut -d" " -f1)
-INSTALLED=$(sudo /sbin/tune2fs -l "$ROOTDEV" | awk '/Filesystem created/ {print $5,$4,$7}')
+save_info() {
+  printf "\n"
+  if default_yes "Save system information to ~/$(basename "$info_file")"; then
+    printf "Writing system information to ~/%s\n" "$(basename "$info_file")"
+    cp -v "$tmp_file" "$info_file"
+    chmod 664 "$info_file"
+  else
+    printf "System information was not written to ~/%s\n" "$(basename "$info_file")"
+  fi
+}
 
-# CPU, RAM and video
+rename_mnt_pt() {
+  local ts_path="/run/timeshift/backup"
+  ts_drv=$(mount | awk '/timeshift/ {print $3}' | cut -d' ' -f1)
+  printf "\nRename the mountpoint for %s to:\n" "$ts_drv"
+  PS3="Select the appropriate mountpoint: "
+  select opt in "/home" "/data" "/ (root)" "/run/timeshift/backup"; do
+    case $REPLY in
+      1 )
+        sed -i '/timeshift/s/run\/timeshift\/backup/home/' "$tmp_file"
+        printf "%s mountpoint changed to /home\n" "$ts_drv"
+        break
+      ;;
+      2 )
+        sed -i '/timeshift/s/run\/timeshift\/backup/data/' "$tmp_file"
+        printf "%s mountpoint changed to /data\n" "$ts_drv"
+        break
+      ;;
+      3 )
+        sed -i '/timeshift/s/run\/timeshift\/backup//' "$tmp_file"
+        printf "%s mountpoint changed to /]n" "$ts_drv"
+        break
+      ;;
+      4 )
+        printf "%s mountpoint left as is." "$ts_drv"
+        break
+      ;;
+      * )
+        printf "%s Invalid choice! Select 1, 2, 3, or 4\n" >&2 "$red_error"
+    esac
+  done
+}
 
-CPUINFO=$(/usr/bin/lscpu | grep 'Model name' | cut -f 2 -d ":" | awk '{$1=$1}1' | sed "s/([^)]*)//g")
-THREADS=$(/usr/bin/nproc --all)
-PHYSMEM=$(/usr/bin/free -h | awk '/^Mem:/ {printf "%.0f\n", $2 + 0.5}')
-RAMTYPE=$(sudo /usr/sbin/dmidecode --type 17 | awk '/DDR/ {print $2; exit}')
-VIDEO=$(/usr/bin/lspci | grep 'VGA' | cut -d ' ' -f5-)
+ff_fix() {
+  printf "Form factor not displayed in Hard Disk Information.\n" >&2
+  PS3="Select form factor: " >&2
+  options=( "2.5 inch" "3.5 inch" "less than 1.8 inch" "ignore")
+  select opt in "${options[@]}"; do
+    case "$REPLY" in
+      1 )
+        hd_ff="2.5 inch"
+        break
+      ;;
+      2 )
+        hd_ff="3.5 inch"
+        break
+      ;;
+      3 )
+        hd_ff="less than 1.8 inch"
+        break
+      ;;
+      4 )
+        break
+      ;;
+      * )
+        printf "%s Invalid choice!$ Choose 1, 2, 3, or 4\n1" >&2 "$red_error"
+    esac
+  done
+}
 
-# Network
+mfg_info() {
+	local dmi_dir="/sys/class/dmi/id"
+	mfg_version=$(cat $dmi_dir/product_version)
+	[[ -z "${mfg_version// }" ]] && mfg_version="Not specified"
+	mfg_serial=$(sudo cat $dmi_dir/product_serial)
+	[[ -z "${mfg_serial// }" ]] && mfg_serial="Not specified"
+	printf "%-14s %s\n" "Manufacturer:" "$(cat $dmi_dir/sys_vendor)"
+	printf "%-14s %s\n" "Product name:" "$(cat $dmi_dir/product_name)"
+	printf "%-14s %s\n" "Version:" "$mfg_version"
+	printf "%-14s %s\n" "Serial number:" "$mfg_serial"
+}
 
-ETHINT=$(/usr/bin/nmcli dev | awk '/ethernet/ {print $1}')
-WIFIINT=$(/usr/bin/nmcli dev | awk '/wifi/ {print $1}')
-ETHERNETDEV=$(/usr/bin/lspci | grep 'Ethernet controller' | cut -d ' ' -f4-)
-WIRELESSDEV=$(/usr/bin/lspci | grep 'Network controller' | cut -d ' ' -f4-)
+os_info() {
+	r_p=$(df -P / | awk '/dev/ {print $1}')
+	created_date=$(sudo /usr/sbin/tune2fs -l "$r_p" | awk '/created:/ {print $(NF-2),$(NF-3),$NF}')
+	printf "\n%-19s %s\n" "Operating System:" "$(uname -o)"
+	printf "%-19s %s\n" "Distribution:" "$(get_distribution)"
+	printf "%-19s %s\n" "Filesystem created:" "$created_date"
+}
 
-# Battery
+cpu_info() {
+  model=$(lscpu | awk -F: '/Model name:/ {print $NF}' | awk '{$1=$1}1' | sed 's/([^)]*)//g')
+  arch=$(lscpu | awk '/Architecture:/ {print $NF}')
+  threads=$(lscpu | awk '/CPU\(s\)/ {print $NF;exit}')
+	printf "\n%-9s %s, %s, %s threads \n" "CPU:" "$model" "$arch" "$threads"
+}
 
-BATTERY=$(/usr/bin/upower -e | grep 'BAT' | cut -d'_' -f2)
+memory_info() {
+	phys_mem=$(sudo lshw -class memory -short -quiet | awk '/System/ {print $(NF-2)}' | sed 's/GiB/ GB/')
+	mem_type=$(sudo dmidecode --type 17 | awk '/Type:/ {print $NF; exit}')
+	mem_max=$(sudo dmidecode --type 16 | awk -F: '/Capacity/ {print $NF; exit}' | sed 's/^ //')
+	printf "%-9s %s %s (%s maximum)\n" "Memory:" "$phys_mem" "$mem_type" "$mem_max"
+}
 
-# Write data to file in user's home directory
+graphics_info() {
+	printf "%-9s %s\n" "Graphics:" "$(/usr/bin/lspci | awk -F: '/VGA/ {print $NF}' | sed 's/^ //')"
+}
 
+wired_info() {
+	eth_int=$(sudo /usr/bin/lshw -class network -quiet | awk '/name: e/ {print $NF}')
+	if [[ -n "$eth_int" ]]; then
+		ethernet_dev=$(/usr/bin/lspci | awk -F: '/Ethernet controller/ {print $NF}' | sed 's/^ //')
+		e_mac=$(cat /sys/class/net/"${eth_int}"/address)
+		printf "\nEthernet: %s\n" "$ethernet_dev"
+    printf "%15s %s\n" "Device name:" "$eth_int" "MAC address:" "$e_mac"
+	fi
+}
+
+wireless_info() {
+	wifi_int=$(sudo /usr/bin/lshw -class network -quiet | awk '/name: w/ {print $NF}')
+	if [[ -n "$wifi_int" ]]; then
+		wireless_dev=$(/usr/bin/lspci | awk -F: '/Network controller/ {print $NF}' | sed 's/^ //')
+		w_mac=$(cat /sys/class/net/"${wifi_int}"/address)
+		printf "\nWireless: %s\n" "$wireless_dev"
+	  printf "%15s %s\n" "Device name:" "$wifi_int" "MAC address:" "$w_mac"
+	fi
+}
+
+ssd_hd_info() {
+	printf "\nHard Disk Information:\n"
+	hd_data=$(mktemp -q) || die "Failed to create temporary file." 1
+	for disk in /dev/sd[a-z]; do
+		sudo hdparm -I "${disk}" 2>/dev/null | tee "$hd_data" > /dev/null
+    printf "%s\n" "$(grep -w dev "$hd_data")"
+    printf "   %-15s%s\n" "Model Number:" "$(awk -F: '/Model/ {print $NF}' "$hd_data" | sed 's/^ *//g')"
+    printf "   %-15s%s\n" "Serial Number:" "$(awk -F: '/Serial N/ {print $NF}' "$hd_data" | sed 's/^ *//g')"
+    printf "   %-15s%s\n" "Capacity:" "$(awk '/GB/ {print $(NF-1),$NF}' "$hd_data" | sed 's/[)(]//g')"
+    hd_ff=$(awk -F: '/Form Factor/ {print $NF}' "$hd_data" | sed 's/^ //')
+    [[ -z "$hd_ff" ]] && ff_fix
+    printf "   %-15s%s" "Form Factor:" "$hd_ff"
+    hd_rpm=$(awk -F: '/Rotation/ {print $NF}' "$hd_data" | sed 's/^ //')
+    case "$hd_rpm" in
+    	[0-9]* ) printf " %s-rpm Hard Disk Drive\n" "$hd_rpm" ;;
+    	* ) printf " %s\n" "$hd_rpm" ;;
+    esac
+	done
+}
+
+nvme_info() {
+  printf "\nNVMe Information\n"
+  nvme_data=$(sudo /usr/sbin/nvme list | tail -n+3)
+  for devline in "${nvme_data[@]}"; do
+    printf "%s\n" "$(echo "$devline" | awk '/dev/ {print $1}' | cut -d'/' -f3)"
+    printf "   %-15s%s\n" "Model Number:" "$(echo "$devline" | awk '/dev/ {print $3,$4}' | sed 's/ [0-9].*$//')"
+    printf "   %-15s%s\n" "Serial Number:" "$(echo "$devline" | awk '/dev/ {print $2}')"
+    printf "   %-15s%s\n" "Capacity:" "$(echo "$devline" | awk '/dev/ {print $(NF-7),$(NF-6)}')"
+  done
+}
+
+partition_info() {
+	printf "\nPartition Information:\n"
+	lsblk -o NAME,SIZE,TYPE,MOUNTPOINT,MODEL,SERIAL
+}
+
+battery_info() {
+  printf "\nBattery Information:\n"
+  battery_name=$(find /sys/class/power_supply/ -name "BAT*" | awk -F/ '/BAT/ {print $5}')
+  if [[ -n "$battery_name" ]]; then
+    battery_path="/sys/class/power_supply/$battery_name"
+    battery_data=$(cat "$battery_path"/uevent)
+    battery_serial=$(echo "$battery_data" | awk -F= '/SERIAL/ {print $NF}')
+    [[ -z "$battery_serial" || "$battery_serial" == " " ]] && battery_serial="Not specified"
+    printf "%s\n" "$battery_name"
+    printf "   %-15s%s\n" "Manufactuer:" "$(echo "$battery_data" | awk -F= '/MANUFACTURER/ {print $NF}' | sed 's/^ //')"
+    printf "   %-15s%s\n" "Model name:" "$(echo "$battery_data" | awk -F= '/MODEL/ {print $NF}')"
+    printf "   %-15s%s\n" "Serial number:" "$battery_serial"
+    printf "   %-15s%s\n" "Technology:" "$(echo "$battery_data" | awk -F= '/TECHNOLOGY/ {print $NF}')"
+  else
+    printf "No battery detected\n"
+  fi
+}
+
+## Execution ##
+
+tmp_file=$(mktemp -q) || die "Failed to create temporary file." 1
+trap cleanup EXIT
+user_in_sudo
+check_dependencies
 clear
 {
-  echo "System-Info ($VERSION), Copyright 2019-2021, Richard Romig"
-  echo $'\n'$"System information for $LHOST as of $TODAY"
-  echo "Manufacturer:  $MFGNAME"
-  echo "Product name:  $PRODNAME"
-  echo "Version:       $VERNAME"
-  echo "Serial number: $SERNUM"
-  echo $'\n'$"Operating System:   $OSNAME"
-  echo "Distribution:       $DISTRO"
-  echo "Filesystem created: $INSTALLED"
-  echo $'\n'$"Hardware:"
-  echo "  CPU:  $CPUINFO (Threads: $THREADS)"
-  echo "  RAM:  $PHYSMEM GB $RAMTYPE"
-  echo "  Graphics:"
-  echo "    $VIDEO"
-  if [ -n "$ETHERNETDEV" ]; then
-    echo "  Ethernet:"
-    echo "    Device name: $ETHINT"
-    echo "    $ETHERNETDEV"
-    echo "    MAC address: $(/bin/cat "/sys/class/net/$ETHINT/address")"
-  fi
-  if [ -n "$WIRELESSDEV" ]; then
-    echo "  Wireless:"
-    echo "    Device name: $WIFIINT"
-    echo "    $WIRELESSDEV"
-    echo "    MAC address: $(/bin/cat "/sys/class/net/$WIFIINT/address")"
-  fi
-  echo $'\n'$"Hard Disk information:"
-  for DISK in /dev/sd[a-z]
-  do
-    HDDEV=$(sudo /sbin/hdparm -I "${DISK}" 2>/dev/null | grep -e '/dev/')
-    HDMODEL=$(sudo /sbin/hdparm -I "${DISK}" | grep 'Model Number' | cut -c 22-)
-    HDSERIAL=$(sudo /sbin/hdparm -I "${DISK}" | awk '/Serial Number/ {print $3}')
-    HDSIZE=$(sudo /sbin/hdparm -I "${DISK}"| awk '/GB/ {print $9" "$10}' | sed 's/[)(]//g')
-    echo "$HDDEV"
-    echo "  Model Number : $HDMODEL"
-    echo "  Serial Number: $HDSERIAL"
-    echo "  Capacity: $HDSIZE"
-  done
-  echo $'\n'$"Partition information:"
-  /bin/lsblk -o NAME,SIZE,TYPE,MOUNTPOINT
-  [ -n "$BATTERY" ] && echo $'\n'$"Battery: $BATTERY"
-} | tee "$INFOFILE"
+	printf "System information for %s, as of %s\n\n" "$lhost" "$today"
+	mfg_info
+	os_info
+	cpu_info
+	memory_info
+	graphics_info
+	wired_info
+	wireless_info
+	[[ -b /dev/sda ]] && ssd_hd_info
+  [[ -c /dev/nvme0 ]] && nvme_info
+	partition_info
+	is_laptop && battery_info
+	printf "\n%s v%s (%s)\n" "$_script" "$_version" "$_updated"
+} | tee "$tmp_file"
+
+# Change lsblk timeshift mountpoint to normal partition name.
+grep -q '/run/timeshift/backup' "$tmp_file" && rename_mnt_pt
+
+# Save system info to file in the home directory?
+save_info
 
 exit
diff --git a/upper2lower b/upper2lower
--- a/upper2lower
+++ b/upper2lower
@@ -1,63 +1,102 @@
-#!/bin/bash
+#!/usr/bin/env bash
 ###############################################################################
 # Script Name  : upper2lower
-# Description  : Renames uppercase filenames to lowercase
+# Description  : Renames uppercase in filenames to lowercase
 # Dependencies : rename
-# Args         : filename to be renamed
-# Author       : Richard Romig
-# Email        : rick.romig@gmail.com
-# Comment      : If no filename is passed, renames all files in folder
-#              : to all lowercase
-###############################################################################
-# Copyright (C) 2018  Richard Romig
+# Args         : --all, --help, filename(s) to be renamed
+# Author       : Copyright (C) 2018, Richard Romig
+# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
+# Comment      :
+# License      : GNU General Public License, version 2.0
+##############################################################################
+
+# Copyright © 2023, Richard B. Romig
 # Email: rick.romig@gmail.com
-#
+# 
 # This program is free software; you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
 # the Free Software Foundation; either version 2 of the License, or
 # (at your option) any later version.
-#
+# 
 # This program is distributed in the hope that it will be useful,
 # but WITHOUT ANY WARRANTY; without even the implied warranty of
-# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 # GNU General Public License for more details.
-#
+# 
 # You should have received a copy of the GNU General Public License along
 # with this program. If not, see <https://www.gnu.org/licenses/>.
-###############################################################################
 
-usage()
-{
-  echo "Usage: $SCRIPT [filename]"
-  echo -e "\e[1;31mWARNING!\e[0m If no filename is passed,"
-  echo "$SCRIPT will change ALL filenames in the current directory to lowercase."
-}
+## Shellcheck Directives ##
+# shellcheck source=/home/rick/bin/functionlib
+# shellcheck disable=SC1091
 
-SCRIPT=$(basename "$0")
-FILE="$1"
-VERSION="2.0.5"
-UPDATED="24 Feb 2020"
+## Source function library ##
 
-echo "$SCRIPT v$VERSION (Updated: $UPDATED)"
-echo "Changes uppercase letters in files names to lowercase."
-echo "Copyright 2018, Richard Romig"
-
-# if no filename passed then get confirmation from user
-if  [ -z "$FILE"  ]; then
-  usage
-  read -rn1 -p "Are you sure you want to do this? [y/N] " YN
-  case $YN in
-    [Yy]*)
-      rename -v 'y/A-Z/a-z/' ./* ;;
-    *)
-      echo "Exiting the script. No files renamed." ;;
-  esac
-elif [ -f "$FILE" ]; then
-  rename -v 'y/A-Z/a-z/' "$FILE"
+if [[ -x "$HOME/bin/functionlib" ]]; then
+  source "$HOME/bin/functionlib"
 else
-  echo -e "\e[1;31mERROR:\e[0m $FILE does not exist. Try again." >&2
-  usage
+  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
   exit 1
 fi
 
-exit
+## Variables ##
+
+_script=$(basename "$0"); readonly _script
+readonly _version="3.2.2"
+readonly _updated="14 Sep 2023"
+
+## Functions ##
+
+help() {
+  local errcode="${1:-2}"
+  cat << EOF
+Renames filenames in the current directory to all lowercase.
+${orange}Usage:${normal} $_script [option] [filename1] [filename2] ...
+${orange}Options:${normal}
+  --all    change all files in the current directory.
+  --help   display this help message.
+One or more filenames may be entered to be renamed.
+$_script Filename	# Renames filename to lowercase
+$_script Filename1 Filename2	# Renames Filename1 and Filename2 to lowercase
+EOF
+  exit "$errcode"
+}
+
+upper_lower() {
+	local filename="$1"
+	if [[ -f "$filename" ]]; then
+		rename -v 'y/A-Z/a-z/' "$filename"
+	else
+		printf "%s %s not found.\n" "$red_error" "$filename" >&2
+	fi
+}
+
+## Execution ##
+
+if [[ $# -eq 0 ]]; then
+	printf "%s No argument passed.\n" "$red_error" >&2
+  help 1
+elif [[ $# -eq 1 ]]; then
+	case "$1" in
+		"--all" )
+			printf "Renaming all files in the current directory to lowercase.\n"
+			find . -maxdepth 1 -type f -exec rename -v 'y/A-Z/a-z/' {} + | sed 's/\.\///g'
+		;;
+		"--help" )
+			printf "%s help...\n" "$_script"
+			help 0
+		;;
+		--* )
+			printf "%s Invalid argument, %s\n" "$red_error"  "$1" >&2
+			help 1
+		;;
+		* )
+			printf "Renaming %s to lowercase.\n" "$1"
+			upper_lower "$1"
+	esac
+else
+	printf "Renaming selected files to lowercase.\n"
+	for fname in "$@"; do upper_lower "$fname"; done
+fi
+
+leave "$_script v$_version ($_updated)"
