catless - updated from private repository

diff --git a/catless b/catless
--- a/catless
+++ b/catless
@@ -2,17 +2,18 @@
 #############################################################################
 # Script Name  : catless
 # Description  : view text file with less or cat based on terminal window size.
-# Dependencies : functionlib
+# Dependencies : none
 # Arguments    : $1 -> file to be viewed
-# Author       : Copyright (C) 2020, Richard B. Romig, Mosfanet
+# Author       : Copyright ©  2020, Richard B. Romig, LudditeGeek@Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.com
 # Crated       : 02 Jan 2020
-# Updated      : 30 Sep 2024
+# Updated      : 13 Oct 2024
 # Comments     : Checks to see if passed argument is a valid text or json file.
 # TODO (Rick)  :
 # License      : GNU General Public License, version 2.0
 #############################################################################
-# Copyright © 2020, Richard B. Romig
+#
+# Copyright © 2024, Richard B. Romig
 # Email: rick.romig@gmail.com
 #
 # This program is free software; you can redistribute it and/or modify
@@ -27,7 +28,6 @@
 #
 # You should have received a copy of the GNU General Public License along
 # with this program. If not, see <https://www.gnu.org/licenses/>.
-
 ## Shellcheck Directives ##
 # shellcheck source=/home/rick/bin/functionlib
 
@@ -45,15 +45,15 @@ set -eu
 ## Variables ##
 
 script=$(basename "$0"); readonly script
-readonly version="4.7.24274"
+readonly version="4.8.24287"
 
 ## Functions ##
 
 help() {
   local errcode updated
   errcode="${1:-2}"
-  updated="30 Sep 2024"
-  cat << END_HELP
+  updated="13 Oct 2024"
+  cat << _HELP_
 ${orange}$script${normal} v$version (updated $updated)
 Displays a text file using either cat or less depending the number of lines in
 the file and the number of rows in the current terminal window. Less is used when
@@ -61,14 +61,14 @@ the number of lines is greater than the 87% of the rows, otherwise cat is used.
 
  ${green}Usage:${normal} $script filename [-h] [--help]
 
-END_HELP
+_HELP_
   exit "$errcode"
 }
 
 view_file() {
   local catmax filelines textfile
   textfile="$1"
-  # Get 87% of screen
+    # Get 87% of screen
   catmax=$(( $(tput lines)*87/100 ))
   # Find the number of lines in the file
   filelines=$(wc -l "$textfile" | cut -d' ' -f1)
@@ -85,21 +85,21 @@ view_file() {
 
 main() {
   if [[ $# -eq 0 ]]; then
-    printf "%s No argument passed.\n" "$red_error" >&2
+    printf "%s No argument passed.\n" "$RED_ERROR" >&2
     help 1
   elif [[ "$1" = "-h" || "$1" = "--help" ]]; then
     help 0
   elif [[ ! -f "$1" ]]; then
-    printf "%s %s not found.\n" "$red_error" "$1" >&2
+    printf "%s %s not found.\n" "$RED_ERROR" "$1" >&2
     help 2
   elif [[ ! -s "$1" ]]; then
-    printf "%s %s is an empty file.\n" "$red_error" "$1" >&2
+    printf "%s %s is an empty file.\n" "$RED_ERROR" "$1" >&2
     exit 1
   elif file -bL "$1" | grep -qEi "text|json"; then
     view_file "$1"
     exit 0
   else
-    printf "%s %s is not a text file.\n" "$red_error" "$1" >&2
+    printf "%s %s is not a text file.\n" "$RED_ERROR" "$1" >&2
     help 1
   fi
 }
