Redirected 'not a text file' error to stderr.

diff --git a/catless b/catless
--- a/catless
+++ b/catless
@@ -10,7 +10,7 @@
 # TODO (Rick)  :
 # License      : GNU General Public License, version 2.0
 #############################################################################
-# Copyright © 2023, Richard B. Romig
+# Copyright © 2020, Richard B. Romig
 # Email: rick.romig@gmail.com
 # 
 # This program is free software; you can redistribute it and/or modify
@@ -42,8 +42,8 @@ fi
 ## Variables ##
 
 _script=$(basename "$0"); readonly _script
-readonly _version="0.4.0"
-readonly _updated="20 Nov 2023"
+readonly _version="0.4.1"
+readonly _updated="29 Nov 2023"
 
 ## Functions ##
 
@@ -98,7 +98,7 @@ elif is_text "$1"; then
   filename="$1"
   main "$filename"
 else
-  printf "%s %s is not a text file.\n" "$red_error" "$1"
+  printf "%s %s is not a text file.\n" "$red_error" "$1" >&2
   help 1
 fi
 exit
