Added function to determine if file is a text file. Moved execution of viewing file to a function named main. Execution section is checking arguments before calling main function.

diff --git a/catless b/catless
--- a/catless
+++ b/catless
@@ -2,14 +2,29 @@
 #############################################################################
 # Script Name  : catless
 # Description  : view text file with less or cat based on terminal window size.
-# Dependencies : none
-# Arguments    : $1 -> file to be viewed
+# Dependencies : functionlib
+# Arguments    : $1 -> text file to be viewed
 # Author       : Copyright (C) 2020, Richard B. Romig, 02 Jan 2020
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.com
 # Comments     : 
 # TODO (Rick)  :
 # License      : GNU General Public License, version 2.0
 #############################################################################
+# Copyright © 2023, Richard B. Romig
+# Email: rick.romig@gmail.com
+# 
+# This program is free software; you can redistribute it and/or modify
+# it under the terms of the GNU General Public License as published by
+# the Free Software Foundation; either version 2 of the License, or
+# (at your option) any later version.
+# 
+# This program is distributed in the hope that it will be useful,
+# but WITHOUT ANY WARRANTY; without even the implied warranty of
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
+# GNU General Public License for more details.
+# 
+# You should have received a copy of the GNU General Public License along
+# with this program. If not, see <https://www.gnu.org/licenses/>.
 
 ## Shellcheck Directives ##
 # shellcheck source=/home/rick/bin/functionlib
@@ -27,8 +42,8 @@ fi
 ## Variables ##
 
 _script=$(basename "$0"); readonly _script
-readonly _version="0.3.1"
-readonly _updated="10 Nov 2023"
+readonly _version="0.4.0"
+readonly _updated="20 Nov 2023"
 
 ## Functions ##
 
@@ -47,6 +62,27 @@ END_HELP
   exit "$errcode"
 }
 
+is_text() {
+  file -bL --mime "$1" | grep -q '^text' && return "$TRUE" || return "$FALSE"
+}
+
+main() {
+  local textfile="$1"
+  # Get 87% of screen and size of file
+  catmax=$(( $(tput lines)*87/100 ))
+  filesize=$(wc -l "$textfile" | cut -d' ' -f1)
+
+  # View the file
+  box "File: $textfile" "*"
+  if (( filesize < catmax )); then
+	  cat "$textfile"
+	  over_line "$_script $_version (Updated $_updated)" "*"
+  else
+	  less "$textfile"
+	  echo "$_script $_version (Updated $_updated)"
+  fi
+}
+
 ## Execution ##
 
 # Check arguments
@@ -58,21 +94,11 @@ elif [[ "$1" = "-h" || "$1" = "--help" ]]; then
 elif [[ ! -f "$1" ]]; then
   printf "%s %s not found.\n" "$red_error" "$1" >&2
   help 2
-else
+elif is_text "$1"; then
   filename="$1"
-fi
-
-# Get 87% of screen and size of file
-max=$(( $(tput lines)*87/100 ))
-size=$(wc -l "$filename" | cut -d' ' -f1)
-
-# View the file
-box "File: $filename" "*"
-if (( size < max )); then
-	cat "$filename"
-	over_line "$_script $_version (Updated $_updated)" "*"
+  main "$filename"
 else
-	less "$filename"
-	echo "$_script $_version (Updated $_updated)"
+  printf "%s %s is not a text file.\n" "$red_error" "$1"
+  help 1
 fi
 exit
