v 0.1.8 - Added checks to determine system as a laptop and if it is plugged in to AC power.

diff --git a/check-battery b/check-battery
--- a/check-battery
+++ b/check-battery
@@ -29,8 +29,8 @@
 ## Variables ##
 
 readonly SCRIPT=$(basename "$0")
-readonly VERSION="0.1.7"
-readonly UPDATED="09 Aug 2020"
+readonly VERSION="0.1.8"
+readonly UPDATED="21 Sep 2020"
 
 ## Functions ##
 
@@ -90,27 +90,40 @@ battery_condition()
   fi
 }
 
+ac_status()
+{
+  STATUS=$(/usr/bin/upower -i $(/usr/bin/upower -e | grep 'AC') | awk '/online:/ {print $2}')
+  echo -e "\n\e[33mAC Power:\e[0m"
+  echo -n "    Laptop is "
+  [ "$STATUS" = "no" ] && echo -n "not "
+  echo "plugged in."
+}
+
 ## Execution ##
 
 clear
 echo -e "\e[1;33mBattery Status\e[0m"
-
-dpkg -l | grep -qw upower || die "Missing dependency - upower is not installed."
-
-BAT_NAME=$(/usr/bin/upower -e | grep 'BAT' | cut -d "_" -f2)
-
-if [ -z "$BAT_NAME" ]; then
-  echo -e "\n\e[91mNo battery detected.\e[0m"
+if [ -d /proc/acpi/button/lid/ ]; then
+  dpkg -l | grep -qw upower || die "Missing dependency - upower is not installed."
+  # dpkg -l | grep -qw upower || sudo apt install upower -yy"
+  BAT_NAME=$(/usr/bin/upower -e | grep 'BAT' | cut -d "_" -f2)
+  if [ -z "$BAT_NAME" ]; then
+    echo -e "\n\e[91mNo battery detected.\e[0m"
+  else
+    UPOWER_FILE=$(mktemp) || die "Failed to create temporary file." 1
+    trap cleanup EXIT
+    /usr/bin/upower -i "$(/usr/bin/upower -e | grep BAT)" > "$UPOWER_FILE"
+    echo -e "\n\e[33mBattery:\e[0m $BAT_NAME"
+    battery_status
+    battery_capacity
+    battery_condition
+    ac_status
+  fi
 else
-  UPOWER_FILE=$(mktemp) || die "Failed to create temporary file." 1
-  trap cleanup EXIT
-
-  /usr/bin/upower -i "$(/usr/bin/upower -e | grep BAT)" > "$UPOWER_FILE"
-  echo -e "\n\e[33mBattery:\e[0m $BAT_NAME"
-  battery_status
-  battery_capacity
-  battery_condition
+  echo $'\n'$"This system is not a laptop."
+  echo "No battery detected."
 fi
+
 echo -e "\n$SCRIPT v$VERSION (Updated: $UPDATED)"
 
 exit
