check-battery - declared variables local to functions as local, eliminated capacity variable in warning_level(), and changed echo commands to printf.

diff --git a/check-battery b/check-battery
--- a/check-battery
+++ b/check-battery
@@ -7,22 +7,21 @@
 # Author       : Copyright (C) 2020, Richard B. Romig, 30 Jul 2020
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.com
 # Comments     : Obtains battery data from upower utility.
-#              : Inspired by a script by Elias W (eliasw4u on Ezeetalk.com)
 # TODO (Rick)  :
 # License      : GNU General Public License, version 2.0
 # Copyright © 2023, Richard B. Romig
 # Email: rick.romig@gmail.com
-# 
+#
 # This program is free software; you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
 # the Free Software Foundation; either version 2 of the License, or
 # (at your option) any later version.
-# 
+#
 # This program is distributed in the hope that it will be useful,
 # but WITHOUT ANY WARRANTY; without even the implied warranty of
 # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 # GNU General Public License for more details.
-# 
+#
 # You should have received a copy of the GNU General Public License along
 # with this program. If not, see <https://www.gnu.org/licenses/>.
 ###############################################################################
@@ -43,8 +42,8 @@ fi
 ## Variables ##
 
 _script=$(basename "$0"); readonly _script
-readonly _version="0.4.2"
-readonly _updated="05 Oct 2023"
+readonly _version="0.4.3"
+readonly _updated="15 Mar 2024"
 
 ## Functions ##
 
@@ -69,50 +68,55 @@ version() {
 EOF
 }
 
+# shellcheck disable=SC2317 # Don't warn about unreachable commands in this function
+# ShellCheck may incorrectly believe that code is unreachable if it's invoked by variable name or in a trap.
 cleanup() {
   [[ -f "$battery_data" ]] && rm -f "$battery_data"
 }
 
 battery_status() {
-  echo $'\n'"${orange}Battery charge:${normal}"
+  printf "\n%sBattery charge:%s\n" "$orange" "$normal"
   grep --color=never -E "state|to\ full|to\ empty|percentage" "$battery_data"
 }
 
 battery_capacity() {
-  echo $'\n'"${orange}Battery health:${normal}"
+  printf "\n%sBattery health:%s\n" "$orange" "$normal"
   grep --color=never -E "energy-full:|energy-full-design:|capacity:" "$battery_data"
 }
 
 warning_level() {
-  energy_des=$(awk '/energy-full-design:/ {printf "%i", $2}' "$battery_data")
-  energy_act=$(awk '/energy-full:/ {printf "%i", $2}' "$battery_data")
-
-  if [[ "$energy_act" -eq 0 || "$energy_des" -eq 0 ]]; then
-    capacity="0"
+  local energy_design
+  local energy_actual
+  energy_design=$(awk '/energy-full-design:/ {printf "%i", $2}' "$battery_data")
+  energy_actual=$(awk '/energy-full:/ {printf "%i", $2}' "$battery_data")
+  if [[ "$energy_actual" -eq 0 || "$energy_design" -eq 0 ]]; then
+    echo "0"
   else
-    capacity=$(awk '/capacity/ {printf "%i", $2}' "$battery_data")
+    awk '/capacity/ {printf "%i", $2}' "$battery_data"
   fi
-  echo "$capacity"
 }
 
 battery_condition() {
+  local warn
+  local warn_level
   warn_level="$(warning_level)"
-  # warn_level="$?"
   if [[ "$warn_level" -le "0" ]]; then
     warn="\U1F4A9"
-    echo -e "    ${red}Replace the battery!${normal}  $warn"
+    printf "    %sReplace the battery!%s  %s\n" "$red" "$normal" "$warn"
   elif [[ "$warn_level" -le "35" ]]; then
     warn="\U1F622"
-    echo -e "    ${red}The battery should be replaced.${normal}  $warn"
+    printf "    %sThe battery should be replaced.%s  %s\n" "$red" "$normal" "$warn"
   elif [[ "$warn_level" -le "65" ]]; then
     warn="\U26A0\UFE0F"
-    echo -e "    ${orange}The battery is getting weak.${normal}  $warn"
+    printf "    %sThe battery is getting weak.%s  %s\n" "$orange" "$normal" "$warn"
   else
-    echo -e "    ${green}The battery is in good condition.${normal}"
+    printf "    %sThe battery is in good condition.%s\n" "$green" "$normal"
   fi
 }
 
 battery_specs() {
+  local battery_serial
+  local battery_tech
   battery_serial=$(awk -F: '/serial/ {print $NF}' "$battery_data" | awk '{$1=$1}1')
   [[ -z "$battery_serial" ]] && battery_serial="Not specified"
   battery_tech=$(awk -F: '/technology/ {print $NF}' "$battery_data" | awk '{$1=$1}1')
@@ -126,21 +130,21 @@ battery_specs() {
 
 
 ac_status() {
+  local status
   status=$(/usr/bin/upower -i "$(/usr/bin/upower -e | grep 'AC')" | awk '/online:/ {print $NF}')
-  echo $'\n'"${orange}AC Power:${normal}"
-  echo -n "    Laptop is "
-  [[ "$status" = "no" ]] && echo -n "not "
-  echo "plugged in to AC power."
+  printf "\n%sAC Power:%s\n" "$orange" "$normal"
+  printf "    Laptop is "
+  [[ "$status" = "no" ]] && printf "not "
+  printf "plugged in to AC power.\n"
 }
 
 hidpp_battery() {
-  if /usr/bin/upower -e | grep -q mouse_hidpp_battery; then
-    hidpp_data=$(/usr/bin/upower -i "$(/usr/bin/upower -e | grep hidpp)")
-    echo $'\n'$"${orange}HID++ Battery:${normal}"
-    echo "    Device: $(echo "$hidpp_data" | awk '/native-path/ {print $NF}')"
-    echo -n "    $(echo "$hidpp_data" | awk '/model/ {print $NF}'):   "
-    echo "$hidpp_data" | awk '/percentage/ {print $NF}'
-  fi
+  local hidpp_data
+  hidpp_data=$(/usr/bin/upower -i "$(/usr/bin/upower -e | grep hidpp)")
+  printf "\n%sHID++ Battery:%s\n" "$orange" "$normal"
+  printf "    Device: %s\n" "$(echo "$hidpp_data" | awk '/native-path/ {print $NF}')"
+  printf "    %s:   " "$(echo "$hidpp_data" | awk '/model/ {print $NF}')"
+  printf "%s\n" "$(echo "$hidpp_data" | awk '/percentage/ {print $NF}')"
 }
 
 ## Execution ##
@@ -157,31 +161,29 @@ if [[ $# -gt 0 ]]; then
       exit
     ;;
     * )
-    echo "${lightred}Invalid argument:${normal} $1" >&2
+    printf "%sInvalid argument:%s %s\n" "$lightred" "$normal" "$1" >&2
     help 2
   esac
 fi
 
-echo -e "${bold}${orange}Battery Information${normal}"
+printf "%s%sBattery Information%s\n" "$bold" "$orange" "$normal"
 if [[ -d /proc/acpi/button/lid/ ]]; then
   if /usr/bin/upower -e | grep -q 'BAT'; then
     battery_data=$(mktemp) || die "Failed to create temporary file." 1
     trap cleanup EXIT
     /usr/bin/upower -i "$(/usr/bin/upower -e | grep BAT)" > "$battery_data"
-    echo $'\n'$"${orange}Battery:${normal} $(awk '/native-path:/ {print $NF}' "$battery_data")"
+    printf "\n%sBatter:%s %s\n" "$orange" "$normal" "$(awk '/native-path:/ {print $NF}' "$battery_data")"
     battery_status
     battery_capacity
     battery_condition
     battery_specs
   else
-    echo $'\n'"${lightred}No battery detected.${normal}" >&2
+    printf "\n%sNo battery detected.%s\n" "$lightred" "$normal" >&2
   fi
   ac_status
-  hidpp_battery
+  /usr/bin/upower -e | grep -q mouse_hidpp_battery && hidpp_battery
 else
-  echo $'\n'$"This system is not a laptop." >&2
+  printf "\nThis system is not a laptop.\n" >&2
 fi
-
-echo $'\n'$"$_script v$_version ($_updated)"
-
+printf "\n%s v%s (%s)\n" "$_script" "$_version" "$_updated"
 exit
