check-updates: added tmp file to hold output from 'apt-get dist-upgrade -s' to use for summary and package count.

diff --git a/check-updates b/check-updates
--- a/check-updates
+++ b/check-updates
@@ -2,33 +2,17 @@
 ###############################################################################
 # Script Name  : check-updates
 # Description  : check for updates and install if necessary.
-# Dependencies : ~/bin/functionlib, apt, apt-get (optional: nala, flatpak, cinnamon-spice-updater)
+# Dependencies : apt-get (optional: nala, flatpak, cinnamon-spice-updater)
 # Arguments    : see help()
 # Author       : Copyright (C) 2018, Richard Romig, Mosfanet
 # Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
 # Crated       : 08 Dec 2018
-# Updated      : 10 Apr 2025
+# Updated      : 13 Apr 2025
 # Comments     : For Debian/Ubuntu-based Linux distributions
 #              : apt-get is better suited than apt for use in scripts.
 #              : Lists available updates. Updates can be deferred.
 # TODO (rick)  :
-# License      : GNU General Public License, version 2.0 <https://github.com/RickRomig/bashscripts>
-###############################################################################
-# Copyright © 2018, Richard B. Romig
-# Email: rick.romig@gmail.com
-#
-# This program is free software; you can redistribute it and/or modify
-# it under the terms of the GNU General Public License as published by
-# the Free Software Foundation; either version 2 of the License, or
-# (at your option) any later version.
-#
-# This program is distributed in the hope that it will be useful,
-# but WITHOUT ANY WARRANTY; without even the implied warranty of
-# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
-# GNU General Public License for more details.
-#
-# You should have received a copy of the GNU General Public License along
-# with this program. If not, see <https://www.gnu.org/licenses/>.
+# License      : GNU General Public License, version 2.0
 ###############################################################################
 
 ## Shellcheck Directives ##
@@ -48,10 +32,16 @@ set -eu
 ## Global Variables ##
 
 script=$(basename "$0"); readonly script
-readonly version="6.3.25100"
+readonly version="7.0.25103"
 SECONDS=0
 
 ## Functions ##
+
+# shellcheck disable=SC2317 # Don't warn about unreachable commands in this function
+# ShellCheck may incorrectly believe that code is unreachable if it's invoked by variable name or in a trap.
+cleanup() {
+  [[ -f "$tmp_file" ]] && rm -f "$tmp_file"
+}
 
 help() {
 	local errcode="${1:-2}"
@@ -69,7 +59,7 @@ ${orange}Available options:${normal}
 ${orange}Notes:${normal}
   If nala is not installed, defers to using apt-get
 _HELP_
-  exit 0
+  exit "$errcode"
 }
 
 check_disk_space() {
@@ -79,7 +69,7 @@ check_disk_space() {
 	r_used=$(echo "$df_stats" | cut -d ' ' -f2)
 	r_perc=$(echo "$df_stats" | cut -d ' ' -f4)
 	r_avail=$(echo "$df_stats" | cut -d ' ' -f3)
-	printf "\nDisk space used (root): %s / %s %s used, %s available.\n" "$r_used" "$r_size" "$r_perc" "$r_avail"
+  printf "\nDisk space used (root): %s / %s %s used, %s available.\n" "$r_used" "$r_size" "$r_perc" "$r_avail"
 }
 
 check_reboot_required() {
@@ -122,6 +112,7 @@ clean_apt_cache() {
 
 remove_orphans() {
   local npkgs
+  # npkgs=$(apt-get autoremove -s | grep "^[[:digit:]]\+ upgraded" | cut -d' ' -f6)
   npkgs=$(apt-get autoremove -s | awk '$2 == "upgraded," {print $6}')
   printf "\n%sRemoving orphaned packages...%s\n" "$orange" "$normal"
   if [[ "$npkgs" -gt 0 ]]; then
@@ -166,41 +157,16 @@ update_flatpak() {
     printf "User installations...\n"
     flatpak update --user --noninteractive --force-remove --assumeyes
     printf "System-wide installations...\n"
-    sudo flatpak update --system --noninteractive --force-remove --assumeyes 2> /dev/null
-    printf "\n"
+    sudo flatpak update --system --noninteractive --force-remove --assumeyes  2> /dev/null
+    # printf "\n"
   else
-    printf "No Flatpaks installed.\n\n"
+    printf "No Flatpaks installed.\n"
   fi
 }
 
 update_spices() {
   printf "\n%sCinnamon Spices:%s\n" "$orange" "$normal"
   cinnamon-spice-updater --update-all
-}
-
-update_summary() {
-	local fields nupg nnew nrem ndef
-  fields="$1"
-	nupg=$(echo "$fields" | cut -d' ' -f1)
-	nnew=$(echo "$fields" | cut -d' ' -f2)
-	nrem=$(echo "$fields" | cut -d' ' -f3)
-	ndef=$(echo "$fields" | cut -d' ' -f4)
-  printf "%sPackage summary:%s\n" "$orange" "$normal"
-  printf "%s|%s|%s|%s\n" "$nupg" "$nnew" "$nrem" "$ndef" | column -t -s "|" -N UPGRADE,NEW,REMOVE,HOLD
-}
-
-list_uprgradable() {
-  apt list --upgradable 2>/dev/null | sed '1d' | cut -d'/' -f1
-}
-
-count_updates() {
-  local nupdates fields field1 field2
-  fields="$1"
-  field1=$(echo "$fields" | cut -d' ' -f1)
-  field2=$(echo "$fields" | cut -d' ' -f2)
-  field3=$(echo "$fields" | cut -d' ' -f3)
-  nupdates=$((field1 + field2 + field3))
-  printf "%s" "$nupdates"
 }
 
 nala_update() {
@@ -215,6 +181,31 @@ nala_update() {
     printf "Autoremove and autopurge deferred.\n"
   fi
   printf "\n"
+}
+
+apt_update() {
+  local nupd #summary
+  printf "%sChecking for updates...%s\n" "$orange" "$normal"
+  update_apt_cache
+  nupd=$(count_updates)
+  if (( nupd > 0 )); then
+    printf "%sSummary:%s\n" "$orange" "$normal"
+    sed -ne '/^Calculating/,/newly/p' "$tmp_file" | sed '1d'
+    apt_menu "$nupd"
+  else
+    printf "%sSummary:%s\n" "$orange" "$normal"
+    sed -ne '/^Calculating/,/newly/p' "$tmp_file" | sed '1d'
+  fi
+}
+
+count_updates() {
+	local field1 field2 field3
+	local -i count=0
+	field1=$(awk '$8 == "remove" {print $1}' "$tmp_file")
+	field2=$(awk '$8 == "remove" {print $3}' "$tmp_file")
+	field3=$(awk '$8 == "remove" {print $6}' "$tmp_file")
+	count=$((field1 + field2 + field3))
+	echo "$count"
 }
 
 apt_menu() {
@@ -268,34 +259,14 @@ apt_menu() {
 	done
 }
 
-apt_update() {
-  local nupd summary
-  printf "%sChecking for updates...%s\n" "$orange" "$normal"
-  update_apt_cache
-  summary=$(apt-get dist-upgrade -s |  awk '$2 == "upgraded," {print $1,$3,$6,$(NF-2)}')
-  nupd=$(count_updates "$summary")
-  if (( nupd > 0 )); then
-    printf "%sUpgradable packages:%s\n" "$orange" "$normal"
-    list_uprgradable
-    update_summary "$summary"
-    apt_menu "$nupd"
-  else
-    printf "%sPackages are up to date.%s\n" "$orange" "$normal"
-    printf "Packages held:\n"
-    list_uprgradable
-    update_summary "$summary"
-  fi
-}
-
 show_header() {
   local local_host="${HOSTNAME:-$(hostname)}"
   clear
   cat << _HEADER_
 ${bold}${orange}$script $version
-System: $local_host $(local_ip)
+System: $local_host ($(local_ip))
 Distro: $(get_distribution)
 Kernel: $(uname -sr)${normal}
-
 _HEADER_
 }
 
@@ -306,7 +277,11 @@ main() {
 	while getopts "$optstr" opt; do
     case "$opt" in
       a )
+        tmp_file=$(mktemp -q) || die "Failed to create temporary file." 1
+        trap cleanup EXIT
+        apt-get dist-upgrade -s > "$tmp_file"
         show_header
+        # cat "$tmp_file"
         check_disk_space
         sudo_login 2
         apt_update
