Updated. See changelog

diff --git a/dos2linux b/dos2linux
--- a/dos2linux
+++ b/dos2linux
@@ -28,25 +28,26 @@
 myscript=$0
 
 usage () {
-	echo "Usage: $myscript file"
-	exit 1
+  echo "Usage: $myscript file"
 }
 
 # check number of arguments
-if  [ -z "$1" ]; then
-	echo "Error: No argments passed."
-	usage
+if [ -z "$1" ]; then
+  echo "ERROR: No argments passed." >&2
+  usage
+  exit 1
 else
-    myfile=$1
+  myfile=$1
 fi
 
 # check if file exists
 if [ ! -f "$myfile" ]; then
-    echo "Error: $myfile not found."
-	usage
+  echo "ERROR: $myfile not found." >&2
+  usage
+  exit 1
 fi
 
 # convert the file
 sed -i.bak -e 's/\r//g'  $myfile
 
-exit 0
+exit
diff --git a/ren-ext b/ren-ext
--- a/ren-ext
+++ b/ren-ext
@@ -25,12 +25,11 @@
 # with this program. If not, see <https://www.gnu.org/licenses/>.
 #####################################################################
 
-function usage {
-	echo "Usage: $myscript extension"
-	echo "Example: $myscript JPG"
-	echo "Supported extensions: BAK, FLV, GIF, htm, HTM, HTML, jpeg, JPG, \
-	MP3, MP4, MPG, mpeg, PDF, PNG, TXT, WMV"
-	exit 1
+usage () {
+  echo "Usage: $myscript extension"
+  echo "Example: $myscript JPG"
+  echo "Supported extensions: BAK, FLV, GIF, htm, HTM, HTML, jpeg, JPG, \
+MP3, MP4, MPG, mpeg, PDF, PNG, TXT, WMV"
 }
 
 myscript=$(basename $0)
@@ -39,86 +38,89 @@ echo "$myscript - bulk renames file extensions in the current diectory."
 echo -e  "Copyright 2018, Richard Romig\n"
 
 # Check for arguments
-if  [ -z "$1"  ]; then
-	echo "Error: Must provide a file extension to be renamed."
-	usage
+if [ -z "$1"  ]; then
+  echo "ERROR: Must provide a file extension to be renamed." >&2
+  usage
+  exit 1
 else
-	ext=$1
+  ext=$1
 fi
 
 shopt -s nocasematch
+
 # Rename file extenssions based on the passed argument
 case $ext in
-	avi)
-        	echo "Renaming .$ext files to .avi"
-		rename -v 's/\.AVI$/\.avi/i' *
-		;;
-	bak)
-        	echo "Renaming .$ext files to .bak"
-		rename -v 's/\.BAK$/\.bak/i' *
-		;;
-	flv)
-		echo "Renaming .$ext files to .flv"
-		rename -v 's/\.FLV$/\.flv/i' *
-		;;
-	gif)
-		echo "Renaming .$ext files to .gif"
-		rename -v 's/\.GIF$/\.gif/i' *
-		;;
-	htm)
-		echo "Renaming .$ext files to .html"
-		rename -v 's/\.htm$/\.html/i' *
-		;;
-	html)
-		echo "Renaming .$ext files to .html"
-		rename -v 's/\.HTML$/\.html/i' *
-		;;
-	jpeg)
-		echo "Renaming .$ext files to .jpg"
-		rename -v 's/\.jpeg$/\.jpg/i' *
-		;;
-	jpg)
-		echo "Renaming .$ext files to .jpg"
-		rename -v 's/\.JPG$/\.jpg/i' *
-		;;
-	mp3)
-		echo "Renaming .$ext files to .mp3"
-		rename -v 's/\.MP3$/\.mp3/i' *
-		;;
-	mp4)
-		echo "Renaming .$ext files to .mp4"
-		rename -v 's/\.MP4$/\.mp4/i' *
-		;;
-	mpg)
-		echo "Renaming .$ext files to .mpg"
-		rename -v 's/\.MPG$/\.mpg/i' *
-		;;
-	mpeg)
-		echo "Renaming .$ext files to .mpg"
-		rename -v 's/\.MPEG$/\.mpg/i' *
-		;;
-	pdf)
-		echo "Renaming .$ext files to .pdf"
-		rename -v 's/\.PDF$/\.pdf/i' *
-		;;
-	png)
-		echo "Renaming .$ext files to .png"
-		rename -v 's/\.PNG$/\.png/i' *
-		;;
-	txt)
-		echo "Renaming .$ext files to .txt"
-		rename -v 's/\.TXT$/\.txt/i' *
-		;;
-	wmv)
-		echo "Renaming .$ext files to .wmv"
-		rename -v 's/\.WMV$/\.wmv/i' *
-		;;
-	*)
-		echo "Error: .$ext is NOT a supported file extension."
-		usage
-		;;
+  avi)
+    echo "Renaming .$ext files to .avi"
+    rename -v 's/\.AVI$/\.avi/i' *
+    ;;
+  bak)
+    echo "Renaming .$ext files to .bak"
+    rename -v 's/\.BAK$/\.bak/i' *
+    ;;
+  flv)
+    echo "Renaming .$ext files to .flv"
+    rename -v 's/\.FLV$/\.flv/i' *
+    ;;
+  gif)
+    echo "Renaming .$ext files to .gif"
+    rename -v 's/\.GIF$/\.gif/i' *
+    ;;
+  htm)
+    echo "Renaming .$ext files to .html"
+    rename -v 's/\.htm$/\.html/i' *
+    ;;
+  html)
+    echo "Renaming .$ext files to .html"
+    rename -v 's/\.HTML$/\.html/i' *
+    ;;
+  jpeg)
+    echo "Renaming .$ext files to .jpg"
+    rename -v 's/\.jpeg$/\.jpg/i' *
+    ;;
+  jpg)
+    echo "Renaming .$ext files to .jpg"
+    rename -v 's/\.JPG$/\.jpg/i' *
+    ;;
+  mp3)
+    echo "Renaming .$ext files to .mp3"
+    rename -v 's/\.MP3$/\.mp3/i' *
+    ;;
+  mp4)
+    echo "Renaming .$ext files to .mp4"
+    rename -v 's/\.MP4$/\.mp4/i' *
+    ;;
+  mpg)
+    echo "Renaming .$ext files to .mpg"
+    rename -v 's/\.MPG$/\.mpg/i' *
+    ;;
+  mpeg)
+    echo "Renaming .$ext files to .mpg"
+    rename -v 's/\.MPEG$/\.mpg/i' *
+    ;;
+  pdf)
+    echo "Renaming .$ext files to .pdf"
+    rename -v 's/\.PDF$/\.pdf/i' *
+    ;;
+  png)
+    echo "Renaming .$ext files to .png"
+    rename -v 's/\.PNG$/\.png/i' *
+    ;;
+  txt)
+    echo "Renaming .$ext files to .txt"
+    rename -v 's/\.TXT$/\.txt/i' *
+    ;;
+  wmv)
+    echo "Renaming .$ext files to .wmv"
+    rename -v 's/\.WMV$/\.wmv/i' *
+    ;;
+  *)
+    echo "ERROR: .$ext is NOT a supported file extension." >&2
+    usage
+    exit 1
+    ;;
 esac
 
 shopt -u nocasematch
 
-exit 0
+exit
diff --git a/upper2lower b/upper2lower
--- a/upper2lower
+++ b/upper2lower
@@ -28,11 +28,10 @@
 myscript=$(basename $0)
 myfile=$1
 
-function usage {
-	echo "Usage: $myscript [filename]"
-	echo "WARNING! If no filename is passed, $myscript will change all \
+usage () {
+  echo "Usage: $myscript [filename]"
+  echo "WARNING! If no filename is passed, $myscript will change all \
 filenames in the current directory to lowercase."
-        exit 1
 }
 
 echo "Upper2Lower - Changes uppercase in files names to lower case."
@@ -40,21 +39,22 @@ echo "Copyright 2018, Richard Romig"
 
 # if no filename passed then get confirmation from user
 if  [ -z "$1"  ]; then
-        echo "WARNING: $myscript without an argument changes all uppercase \
-characters in all filenames in the directory to lowercase."
-        read -p "Are you sure you want to do this? [y/N] " yn
-        case $yn in
-                [Yy]* )
-			rename -v 'y/A-Z/a-z/' *
-                        ;;
-                * )
-			usage
-	                ;;
-        esac
+  Usage
+  read -nl -p "Are you sure you want to do this? [y/N] " yn
+  case $yn in
+    [Yy]* )
+      rename -v 'y/A-Z/a-z/' *
+      ;;
+    * )
+       usage
+       exit
+       ;;
+  esac
 elif [ -e "$myfile" ]; then
-        rename -v 'y/A-Z/a-z/' $myfile
+  rename -v 'y/A-Z/a-z/' $myfile
 else
-        echo "Error: $myfile does not exist. Try again."
-        usage
+  echo "ERROR: $myfile does not exist. Try again." >&2
+  usage
+  exit 1
 fi
-exit 0
+exit
