functionlib - capitalized global variables except colors. Maintaining lowercase until scripts have been updated.

diff --git a/functionlib b/functionlib
--- a/functionlib
+++ b/functionlib
@@ -39,10 +39,13 @@
 
 declare -r TRUE=0
 declare -r FALSE=1
+RED_ERROR=$(printf "\e[91mERROR:\e[0m"); readonly RED_ERROR
+RED_WARNING=$(printf "\e[91mWARNING!\e[0m"); readonly RED_WARNING
 red_error=$(printf "\e[91mERROR:\e[0m"); readonly red_error
 red_warning=$(printf "\e[91mWARNING!\e[0m"); readonly red_warning
 
 # First three octets of the local network. Assumes a /24 private network.
+LOCALNET=$(ip route get 1.2.3.4 | awk '{print $3}' | cut -d '.' -f1,2,3); readonly LOCALNET
 localnet=$(ip route get 1.2.3.4 | awk '{print $3}' | cut -d '.' -f1,2,3); readonly localnet
 
 ## Colors ##
@@ -462,27 +465,27 @@ valid_ip() {
   localip="$(local_ip)"
   if [[ -z "$octet" ]]; then
     status=1
-    printf "%s No argument passed. No host IP.\nEnter the last octet of the target IP address (1 - 254).\n" "$red_error" >&2
+    printf "%s No argument passed. No host IP.\nEnter the last octet of the target IP address (1 - 254).\n" "$RED_ERROR" >&2
   elif [[ "$1" =~ ^[0-9]+$ ]] 2>/dev/null; then
     # Argument is an integer value
     if (( octet > 0 )) && (( octet < 255 )); then
       # Valid address - test if reachable or local machine
       if [[ "$localip" -eq "$octet" ]]; then
         status=2    # Valid address - local machine
-        printf "%s %s.%s is the local client computer.\n" "$red_error" "$localnet" "$octet" >&2
-      elif ping -c 1 "$localnet.$octet" > /dev/null 2>&1; then
+        printf "%s %s.%s is the local client computer.\n" "$RED_ERROR" "$LOCALNET" "$octet" >&2
+      elif ping -c 1 "$LOCALNET.$octet" > /dev/null 2>&1; then
         status=0
-        printf "%s.%s is a valid and reachable IP address.\n" "$localnet" "$octet"
+        printf "%s.%s is a valid and reachable IP address.\n" "$LOCALNET" "$octet"
       else
         status=3
-        printf "%s %s.%s is valid IP address but is unreachable.\nCheck to see if it is on the network.\n" "$red_error" "$localnet" "$octet" >&2
+        printf "%s %s.%s is valid IP address but is unreachable.\nCheck to see if it is on the network.\n" "$RED_ERROR" "$LOCALNET" "$octet" >&2
       fi
     else
       status=4
-      printf "%s %s.%s is not a valid IP address.\nEnter the last octet of the target IP address (1 - 254).\n" "$red_error" "$localnet" "$octet" >&2
+      printf "%s %s.%s is not a valid IP address.\nEnter the last octet of the target IP address (1 - 254).\n" "$RED_ERROR" "$LOCALNET" "$octet" >&2
     fi
   else
-  printf "%s Invalid argument: %s\nEnter the last octet of the target IP address (1 - 254).\n" "$red_error" "$octet" >&2
+  printf "%s Invalid argument: %s\nEnter the last octet of the target IP address (1 - 254).\n" "$RED_ERROR" "$octet" >&2
      status=5
   fi
 
@@ -754,11 +757,11 @@ mount_server() {
   local server_ip share mounted
   server_ip="11"
   share="HP-6005"
-  ping -c3 "$localnet.$server_ip" > /dev/null 2>&1 || die "$share at $localnet.$server_ip is not online."
+  ping -c3 "$LOCALNET.$server_ip" > /dev/null 2>&1 || die "$share at $LOCALNET.$server_ip is not online."
   if [[ -d "$HOME/mnt/$share/" ]]; then
     mounted=$(mount | grep "$share")
     if [[ -z "$mounted" ]]; then
-      sshfs -o follow_symlinks rick@"$localnet.$server_ip:/home/rick" "$HOME/mnt/$share/"
+      sshfs -o follow_symlinks rick@"$LOCALNET.$server_ip:/home/rick" "$HOME/mnt/$share/"
       echo "$share has been mounted."
     else
       echo "$share is already mounted"
@@ -766,7 +769,7 @@ mount_server() {
   else
     # Create the mount point.
     mkdir -p "$HOME/mnt/$share/"
-    sshfs -o follow_symlinks rick@"$localnet.$server_ip:/home/rick" "$HOME/mnt/$share/"
+    sshfs -o follow_symlinks rick@"$LOCALNET.$server_ip:/home/rick" "$HOME/mnt/$share/"
     echo "$share has been created and mounted."
   fi
 }
@@ -803,18 +806,18 @@ mount_nas() {
   local server_ip share mounted
   server_ip="4"
   share="NASD97167"
-  ping -c3 "$localnet.$server_ip" > /dev/null 2>&1 || die "$share at $localnet.$server_ip is not online."
+  ping -c3 "$LOCALNET.$server_ip" > /dev/null 2>&1 || die "$share at $LOCALNET.$server_ip is not online."
   if [[ -d "$HOME/mnt/$share/" ]]; then
     mounted=$(mount | grep "$share")
     if [[ -z "$mounted" ]]; then
-      sshfs -o follow_symlinks rick@"$localnet.$server_ip:" "$HOME/mnt/$share/"
+      sshfs -o follow_symlinks rick@"$LOCALNET.$server_ip:" "$HOME/mnt/$share/"
       echo "$share has been mounted."
     else
       echo "$share is already mounted"
     fi
   else
     mkdir -p "%HOME/mnt/$share/"    # Create the mount point.
-    sshfs -o follow_symlinks rick@"$localnet.$server_ip:" "$HOME/mnt/$share/"
+    sshfs -o follow_symlinks rick@"$LOCALNET.$server_ip:" "$HOME/mnt/$share/"
     echo "$share has been created and mounted."
   fi
 }
@@ -891,10 +894,10 @@ y_or_n() {
         return "$FALSE"
       ;;
       '' )
-        printf "%s Response required -- try again.\n" "$red_warning" >&2
+        printf "%s Response required -- try again.\n" "$RED_WARNING" >&2
       ;;
       * )
-        printf "%s Invalid choice. Enter y or n.\n" "$red_error" >&2
+        printf "%s Invalid choice. Enter y or n.\n" "$RED_ERROR" >&2
     esac
   done
 }
@@ -920,10 +923,10 @@ yes_or_no() {
         return "$FALSE"
       ;;
       '' )
-        printf "%s Response required -- try again.\n" "$red_warning" >&2
+        printf "%s Response required -- try again.\n" "$RED_WARNING" >&2
       ;;
       * )
-        printf "%s Invalid choice. Enter yes or no.\n" "$red_error" >&2
+        printf "%s Invalid choice. Enter yes or no.\n" "$RED_ERROR" >&2
     esac
   done
 }
@@ -949,7 +952,7 @@ default_yes() {
         return "$FALSE"
       ;;
       * )
-        printf "%s Invalid choice. Enter y or n.\n" "$red_error" >&2
+        printf "%s Invalid choice. Enter y or n.\n" "$RED_ERROR" >&2
     esac
   done
 }
@@ -975,7 +978,7 @@ default_no() {
         return "$FALSE"
       ;;
       * )
-        printf "%s Invalid choice. Enter y or n.\n" "$red_error" >&2
+        printf "%s Invalid choice. Enter y or n.\n" "$RED_ERROR" >&2
     esac
   done
 }
