iru-micro - changed red_error to uppercase.

diff --git a/iru-micro b/iru-micro
--- a/iru-micro
+++ b/iru-micro
@@ -227,12 +227,12 @@ while getopts "$optstr" opt; do
       compare_versions
     ;;
     ? )
-      echo "$red_error Invalid option -${OPTARG}" >&2
+      echo "$RED_ERROR Invalid option -${OPTARG}" >&2
       help 2
   esac
   noOpt=0
 done
-[[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$red_error" >&2; help 1; }
+[[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help 1; }
 shift "$(( OPTIND - 1 ))"
 box "$_script v$_version"
 exit
