iru-marktext - changed red_error to uppercase.

diff --git a/iru-marktext b/iru-marktext
--- a/iru-marktext
+++ b/iru-marktext
@@ -241,12 +241,12 @@ main() {
 			compare_versions "$new_ver"
 		;;
 		? )
-			echo "$red_error Invalid option -${OPTARG}" >&2
+			echo "$RED_ERROR Invalid option -${OPTARG}" >&2
       help 2
 	esac
 	noOpt=0
 	done
-	[[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$red_error" >&2; help 1; }
+	[[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help 1; }
 	shift "$(( OPTIND - 1 ))"
 	over_line "$script v$version"
 	exit
