updated scripts

diff --git a/ren-ext b/ren-ext
--- a/ren-ext
+++ b/ren-ext
@@ -30,34 +30,33 @@ function usage {
 	echo "Example: $MYSCRIPT JPG"
 	echo "Supported extensions: BAK, GIF, htm, HTM, HTML, jpeg, JPG, MP3, \
 MP4, PDF, PNG, TXT"
+	exit 1
 }
 
 MYSCRIPT=$(basename $0)
 
-echo "$MYSCRIPT - bulk renames file extensions in the current diectory."
-echo ""
+echo "$MYSCRIPT - bulk renames file extensions in the current diectory.
+echo -e  "Copyright 2018, Richard Romig\n"
 
 # Check for arguments
 if  [ -z "$1"  ]; then
 	echo "Error: Must provide a file extension to be renamed."
 	usage
-	exit 1
 else
 	EXT=$1
 fi
 
-# Check to see if files with the extension exist
+# Check to see if any files with the extension exist
 ls *.$EXT > /dev/null 2>&1
 if [ "$?" != 0 ]; then
 	echo "Error: No .$EXT files exist in the current directory."
 	usage
-	exit 1
 fi
 
 # Rename file extenssions based on the passed argument
 case $EXT in
-    BAK)
-        echo "Renaming .BAK files to .bak"
+	BAK)
+        	echo "Renaming .BAK files to .bak"
 		rename -v 's/\.BAK$/\.bak/' *.BAK
 		;;
 	GIF)
@@ -105,7 +104,7 @@ case $EXT in
 		rename -v 's/\.TXT$/\.txt/' *.TXT
 		;;
 	*)
-		echo "Error: Unsupported file extension, $EXT"
+		echo "Error: $EXT is an unsupported file extension."
 		usage
 		;;
 esac
