v2.0.0 - Simplified script & better check in hosts file

diff --git a/rename-host b/rename-host
--- a/rename-host
+++ b/rename-host
@@ -2,11 +2,12 @@
 #############################################################################
 # Script Name  : ren-hostname
 # Description  : Changes the system hostname
-# Dependencies : awk, nmcli, sed
+# Dependencies : awk, sed
 # Arguments    : new hostname
 # Author       : Richard B. Romig, 06 Nov 2019
 # Email        : rick.romig@gmail.com
 # Comments     : Changes in both /etc/hostname and /etc/hosts
+#              : new hostname argument should be in double-quotes
 #############################################################################
 # Copyright (C) 2020, Richard B. Romig
 # Email: rick.romig@gmail.com
@@ -24,18 +25,13 @@
 # You should have received a copy of the GNU General Public License along
 # with this program. If not, see <https://www.gnu.org/licenses/>.
 
-SCRIPT=$(basename "$0")
-VERSION="1.0.0"
-UPDATED="08 April 2020"
+## Variables ##
 
-die()
-{
-  local MSG="$1"	    # message
-  local EC=${2-1}	    # default exit status 1
+readonly SCRIPT=$(basename "$0")
+readonly VERSION="2.0.0"
+readonly UPDATED="03 May 2020"
 
-  echo -e "\e[1;31mERROR:\e[0m $MSG" >&2
-  exit "$EC"
-}
+## Functions ##
 
 leave()
 {
@@ -55,58 +51,43 @@ usage()
   exit 1
 }
 
+## Execution ##
+
 echo "$SCRIPT v$VERSION"
 echo "(Updated: $UPDATED)"
 echo "Changes the system's hostname."
 
 if [ -z "$1" ]; then
-  echo -e "\e[1;31mError:\3[0m No hostname passed." >&2
+  echo -e "\n\e[1;31mError:\e[0m No hostname passed." >&2
   usage
 else
-  NEWHOST="$1"
-  OLDHOST=$HOSTNAME
-  [ "$NEWHOST" == "$OLDHOST" ] && die "Hostnames are the same, no changes made."
+  readonly NEWHOST="$1"
+  readonly OLDHOST=$HOSTNAME
+  [ "$NEWHOST" == "$OLDHOST" ] && leave "Hostnames are the same, no changes made."
+  sudo ls > /dev/null 2>&1
 fi
-
-# Change hostname in /etc/hostname
 
 echo $'\n'$"Changing the hostname from $OLDHOST to $NEWHOST ..."
-
+# Change hostname in /etc/hostname
 cp -p /etc/hostname /etc/hostname.old > /dev/null 2>&1
-if sudo /usr/bin/nmcli general hostname "$NEWHOST"; then
-  echo "Hostame changed to $NEWHOST"
-else
-  sudo mv /etc/hostname.old /etc/hostname > /dev/null 2>&1
-  die "Operation failed. Hostname not changed."
-fi
-
+sudo sed -i "s/$OLDHOST/$NEWHOST/" /etc/hostname
 # Change hostname in /etc/hosts
-
-echo $'\n'$"Changing hostname in /etc/hosts ..."
-
 cp -p /etc/hosts /etc/hosts.old > /dev/null 2>&1
-OLDHOST=$(awk '/127.0.1.1/ { print $2 }' /etc/hosts)
-if [ "$OLDHOST" != "$NEWHOST" ]; then
-  sudo sed -i "s/$OLDHOST/$NEWHOST/" /etc/hosts
-else
-  rm /etc/hosts.old > /dev/null 2>&1
-  echo "Hostname in /etc/hosts changed by nmcli"
-fi
+sudo sed -i "s/$OLDHOST/$NEWHOST/"
 
-# Compare hostnames in /etc/hostname and /etc/hosts
+# Confirm changes
 
 HOST1=$(cat /etc/hostname)
 HOST2=$(awk '/127.0.1.1/ { print $2 }' /etc/hosts)
-echo "Host name in /etc/hostname = $HOST1"
-echo "Host name in /etc/hosts = $HOST2"
-
+[ -z "$HOST2" ] && HOST2=$(grep -m2 '127.0.0.1' /etc/hosts | tail -n1 | awk '{print $2}')
+echo -e "/etc/hostname = $HOST1\t/etc/hosts = $HOST2"
 if [ "$HOST1" == "$NEWHOST" ] && [ "$HOST2" == "$NEWHOST" ]; then
   rm /etc/hosts.old > /dev/null 2>&1
   rm /etc/hostname.old > /dev/null 2>&1
-  leave "Hostname successfully changed."
+  echo "Hostname successfully changed."
+  leave "Reboot required for changes to take effect."
 else
-  # Revert back to the orginal hostname
   sudo mv /etc/hostname.old /etc/hostname > /dev/null 2>&1
   sudo mv /etc/hosts.old /etc/hosts > /dev/null 2>&1
-  die "Operation failed."
+  leave "Hostname change was unsuccessful. Reverted to the original hostname."
 fi
