2.0.2 - variable names

diff --git a/upper2lower b/upper2lower
--- a/upper2lower
+++ b/upper2lower
@@ -1,5 +1,5 @@
 #!/bin/bash
-#####################################################################
+###############################################################################
 #Script Name  :upper2lower#
 #Description  :Renames uppercase filenames to lowercase
 #Dependencies :rename
@@ -8,7 +8,7 @@
 #Email        :rick.romig@gmail.com
 #Comment      :If no filename is passed, renames all files in folder
 #             :to all lowercase
-#####################################################################
+###############################################################################
 # Copyright (C) 2018  Richard Romig
 # Email: rick.romig@gmail.com
 #
@@ -24,15 +24,16 @@
 #
 # You should have received a copy of the GNU General Public License along
 # with this program. If not, see <https://www.gnu.org/licenses/>.
-#####################################################################
+###############################################################################
+
 usage () {
-  echo "Usage: $MYSCRIPT [filename]"
-  echo -e "\e[1;31mWARNING!\3[0m] If no filename is passed, $MYSCRIPT will change ALL filenames in the current directory to lowercase."
+  echo "Usage: $SCRIPT [filename]"
+  echo -e "\e[1;31mWARNING!\3[0m] If no filename is passed, $SCRIPT will change ALL filenames in the current directory to lowercase."
 }
 
-MYSCRIPT=$(basename "$0")
-MYFILE=$1
-VERSION="2.0.1"
+SCRIPT=$(basename "$0")
+FILE=$1
+VERSION="2.0.2"
 UPDATED="01 Sep 2019"
 
 echo "$SCRIPT v$VERSION (Updated: $UPDATED)"
@@ -40,7 +41,7 @@ echo "Changes uppercase letters in files names to lowercase."
 echo "Copyright 2018, Richard Romig"
 
 # if no filename passed then get confirmation from user
-if  [ -z "$1"  ]; then
+if  [ -z "$FILE"  ]; then
   usage
   read -rn1 -p "Are you sure you want to do this? [y/N] " YN
   case $YN in
@@ -53,11 +54,12 @@ if  [ -z "$1"  ]; then
       ;;
   esac
 elif [ -e "$MYFILE" ]; then
-  rename -v 'y/A-Z/a-z/' "$MYFILE"
+  rename -v 'y/A-Z/a-z/' "$FILE"
 else
-  echo -e "\e[41mERROR: $MYFILE does not exist. Try again.\e[0m" >&2
+  echo -e "\e[41mERROR: $FILE does not exist. Try again.\e[0m" >&2
   usage
   exit 1
 fi
 
 exit
+
