write-iso - changed red_error to uppercase.

diff --git a/write-iso b/write-iso
--- a/write-iso
+++ b/write-iso
@@ -192,11 +192,11 @@ while getopts "$optstr" opt; do
 			write_iso "$iso_file" "$usb_device"
 		;;
 		? )
-			printf "%s Invalid option -%s\n" "$red_error" "$OPTARG" >&2
+			printf "%s Invalid option -%s\n" "$RED_ERROR" "$OPTARG" >&2
 			help 2
 	esac
 	noOpt=0
 done
-[[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$red_error" >&2; help 1; }
+[[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help 1; }
 shift "$(( OPTIND - 1 ))"
 exit
