v1.0.3

diff --git a/yt-dl-install b/yt-dl-install
--- a/yt-dl-install
+++ b/yt-dl-install
@@ -125,7 +125,7 @@ else
       [Yy]*)
         if ! tmpdir=$(mktemp -d)
         then
-          echo -e"\e[1;31mFailed to create temporary directory!\e[0m"
+          echo -e"\e[1;31mFailed to create temporary directory!\e[0m" >&2
           exit 1
         fi
         echo "Creating z-ytdlup.sh script to be run weekly by anacron."
