Version 1.0.3 - Added option create auto-update script

diff --git a/yt-dl-install b/yt-dl-install
--- a/yt-dl-install
+++ b/yt-dl-install
@@ -2,7 +2,7 @@
 ################################################################################
 # Script Name  : yt-dl-install
 # Description  : Installs/updates youtube-dl from https://yt-dl.org
-# Dependencies : apt, chmod, curl
+# Dependencies : apt, chmod, curl, dpkg
 # Arguments    : -i or --info to dispaly information about the script.
 # Author       : Richard B. Romig, 23 May 2019
 # Email        : rick.romig@gmail.com
@@ -27,7 +27,7 @@
 ################################################################################
 
 show_info () {
-  cat << EOF
+  cat << _EOF_
 yt-dl-install $version
 
 1, yt-dl-install installs the most current version of youtude-dl from the
@@ -52,14 +52,24 @@ manager and install the most current version from yt-dl.org to '/usr/local/bin'.
 6. If a version downloaded from yt-dl.org is installed, it will display the
 version number and attempt to update it to the latest version.
 
-7. Please review the README.md, LICENSE, and WARRANTY in the downloaded ZIP
+7. During the installation of youtube-dl from yt-dl.org, will provide the option of creating a script that will automatically check for updates
+
+8. Please review the README.md, LICENSE, and WARRANTY in the downloaded ZIP
 archive for more information. They can also be reviewed in my GitHub repository
 at: https://github.com/RickRomig/bashscripts
 
 Richard Romig (GNU/General Public License version 2.0)
 
-EOF
+_EOF_
 }
+
+# Called by trap to remove the temporary directory upon exit from the script
+
+cleanup () {
+  [ -d "$tmpdir" ] && rm -rf "$tmpdir"
+}
+
+trap cleanup EXIT
 
 version="1.0.3"
 
@@ -78,33 +88,68 @@ sudo ls > /dev/null 2>&1
 
 dpkg -l | grep -qw curl || sudo apt install -yyq curl
 
+# Header
+
 echo -e "\e[1;33myoutube-dl installer and updater, version $version\e[0m"
 echo "Copyright (c) 2019, Richard Romig"
 echo "Licensed under the GNU/General Public License version 2.0"
 
-# Delete older version from /usr/bin/ installed from repositories
+# Delete older version from /usr/bin/ that was installed from the repositories
 
 if dpkg -l | grep -qw youtube-dl
 then
-  echo "Removing the older version installed from the repositories..."
+  echo "Removing the older version installed from the distribution repositories..."
   sudo apt purge -yyq youtube-dl
 fi
 
-# Check if youtube-dl is installed.
-# Assumes installed from https://yt-dl.org
+# Check if youtube-dl is installed from https://yt-dl.org
 
 if which youtube-dl > /dev/null
 then
+  # If installed, attempt to update
   echo "youtube-dl version: $(youtube-dl --version)"
   echo "Updating youtube-dl to the newest version..."
   sudo youtube-dl -U
 else
+  # If not installed, install from maintainter's site
   echo "Installing youtube-dl from https://yt-dl.org..."
   if sudo curl -L https://yt-dl.org/downloads/latest/youtube-dl \
     -o /usr/local/bin/youtube-dl
   then
-    echo "youtube-dl successfully installed to /usr/local/bin"
+    echo "youtube-dl successfully installed at /usr/local/bin"
+    # Set permissions on the downloaded file
     sudo chmod a+rx /usr/local/bin/youtube-dl
+    # Ask to create and install an automatic update script
+    read -rp "Create an anacron script to automatically updte youtbue-dl? [yN] " opt
+    case $opt in
+      [Yy]*)
+        if ! tmpdir=$(mktemp -d)
+        then
+          echo -e"\e[1;31mFailed to create temporary directory!\e[0m"
+          exit 1
+        fi
+        echo "Creating ytdlup.sh script to be run weekly by anacron."
+        # To run monthly or daily, change location to /etc/cron.monthly or /etc/cron.daily
+        {
+          printf "#!/bin/bash\n"
+          echo "set -e"
+          echo 'echo "$(date) $(youtube-dl -U)" >> /var/log/ytdlup.log'
+          printf "lines=\$(wc -l /var/log/ytdlup.log | awk '{ print \$1 }')"
+          echo "if (( lines > 25 )); then"
+          echo "  tail -n 25 /var/log/ytdlup.log > /var/log/ytdlup.tmp"
+          echo "  mv /var/log/ytdlup.tmp /var/log/ytdlup.log"
+          echo "fi"
+          echo "exit"
+        } > "$tmpdir/z-ytdlup.sh"
+        chmod 755 "$tmpdir/z-ytdlup.sh"
+        sudo cp "$tmpdir/z-ytdlup.sh" /etc/cron.weekly/
+        echo "z-ytdlup.sh created in /etc/cron.weekly"
+        echo "Log file will be stored in /var/log/ytdlup.log"
+        ;;
+      *)
+        echo "Creation of youtube-dl update script declined."
+        ;;
+    esac
   else
     status="$?"
     echo -e "\e[1;33myoutube-dl download failed. Exit code: $status\e[0m" >&2
@@ -112,3 +157,4 @@ else
 fi
 
 exit
+
