version 1.0.1

diff --git a/yt-dl-install b/yt-dl-install
--- a/yt-dl-install
+++ b/yt-dl-install
@@ -28,27 +28,28 @@
 
 show_info () {
   cat << EOF
+yt-dl-install $version
+
 1, yt-dl-install installs the most current version of youtude-dl from the
 youtube-dl github site at https://ytdl-org.github.io/youtube-dl/index.html.
-Portions of this script is based upon the download instructions on their
+Portions of this script are based upon the download instructions on the project's
 download page.
 
 2, The script was written for Debian and Ubuntu based distributions but your
 experience may vary.
 
-3. The youtube-dl packages contained in the Ubuntu repositories are often older
-and are not regurlarly whereas the version on yt-dl.org is updated quite
-regurlarly (usually monthly if not more often).
+3. The youtube-dl packages contained in the Debian and Ubuntu repositories are
+often older and are not regurlarly updated whereas the version on yt-dl.org is updated quite regurlarly (usually monthly, if not more often).
 
 4. The version installed by the package manager usually places the application
-in '/usr/bin/' and can't updated unless the version in the Ubuntu repository for
+in '/usr/bin/' and it can't updated unless the version in the repository for
 your distribution is updated.
 
 5. The script will remove the version installed to 'usr/bin' by the package
 manager and install the most current version from yt-dl.org to '/usr/local/bin'.
 
 6. If a version downloaded from yt-dl.org is installed, it will display the
-version number and ask if you want to update to the latest version.
+version number and attempt to update it to the latest version.
 
 7. Please review the README.md, LICENSE, and WARRANTY in the downloaded ZIP
 archive for more information. They can also be reviewed in my GitHub repository
@@ -59,10 +60,13 @@ Richard Romig (GNU/General Public License version 2.0)
 EOF
 }
 
+version="1.0.1"
+
 # Display information about the script
 
 if [ "$1" == "-i" ] || [ "$1" == "--info" ]; then
   show_info
+  exit
 fi
 
 # Check sudo access and start sudo timer
@@ -73,39 +77,37 @@ sudo ls > /dev/null 2>&1
 
 dpkg -l | grep -qw curl || sudo apt install -yyq curl
 
+echo -e "\e[1;33myoutube-dl installer and updater, version $version\e[0m"
+echo "Copyright (c) 2019, Richard Romig"
+echo "Licensed under the GNU/General Public License version 2.0"
+
 # Delete older version from /usr/bin/ installed from repositories
 
-if [ -f /usr/bin/youtube-dl ]; then
-  echo "Deleting the older, repository version..."
+if dpkg -l | grep -qw youtube-dl
+then
+  echo "Removing the older version installed by the package manager..."
   sudo apt remove -yyq youtube-dl
 fi
 
 # Check if youtube-dl is installed.
-# Assumes installed from https;//yt-dl.org to /usr/local/bin/
+# Assumes installed from https;//yt-dl.org
 
 if which youtube-dl > /dev/null
 then
-  # If installed, prompt to update
   echo "youtube-dl version: $(youtube-dl --version)"
-  echo "Do you wish to upgrade to the newest version? [yN]"
-  read -rn1 choice
-  case $choice in
-    [Yy]*)
-      echo $'\n'$"Updating youtube-dl to the newest version..."
-      sudo youtube-dl -U
-      ;;
-    *)
-      echo $'\n'$"No action taken - youtube-dl not updated."
-      ;;
-  esac
+  echo "Updating youtube-dl to the newest version..."
+  sudo youtube-dl -U
 else
-  # Install if not already installed
   echo "Installing youtube-dl from https://yt-dl.org..."
-  sudo curl -L https://yt-dl.org/downloads/latest/youtube-dl \
-   -o /usr/local/bin/youtube-dl
-   # sudo wget https://yt-dl.org/downloads/latest/youtube-dl \
-   # -O /usr/local/bin/youtube-dl
-  sudo chmod a+rx /usr/local/bin/youtube-dl
+  if sudo curl -L https://yt-dl.org/downloads/latest/youtube-dl \
+    -o /usr/local/bin/youtube-dl
+  then
+    echo "youtube-dl successfully installed to /usr/local/bin"
+    sudo chmod a+rx /usr/local/bin/youtube-dl
+  else
+    status="$?"
+    echo "youtube-dl download failed. Exit code: $status" >&2
+  fi
 fi
 
 exit
